{
    "article": {
        "articleNo": "2320636507",
        "articleName": "상가주택",
        "articleSubName": "",
        "cpId": "SERVE",
        "cortarNo": "1168010800",
        "nnhscpPlanBildNo": "18167",
        "tradeBuildingTypeCode": "BILD",
        "exposeStartYMD": "20230515",
        "exposeEndYMD": "20230614",
        "articleConfirmYMD": "20230515",
        "tradeCompleteYN": "N",
        "totalDongCount": 0,
        "articleStatusCode": "R0",
        "articleTypeCode": "D05",
        "realestateTypeCode": "SGJT",
        "realestateTypeName": "상가주택",
        "tradeTypeCode": "A1",
        "tradeTypeName": "매매",
        "verificationTypeCode": "OWNER",
        "verificationTypeName": "집주인",
        "applyYN": "N",
        "directTradeYN": "N",
        "mapLocationIndicationYn": "Y",
        "latitude": "37.5126308",
        "longitude": "127.0408859",
        "pnu": "1168010800102650010",
        "cityNo": "1100000000",
        "cityName": "서울시",
        "divisionName": "강남구",
        "sectionName": "논현동",
        "realtorId": "man2man712",
        "walkingTimeToNearSubway": 7,
        "grandPlanList": [],
        "detailAddress": "",
        "jibunAddress": "265-10",
        "jibunAddressExposureYn": "Y",
        "etcAddress": "블레스홈 제1층 제101호",
        "exposureAddress": "서울시 강남구 논현동 265-10",
        "virtualAddressYn": "N",
        "roomCount": "1",
        "bathroomCount": "1",
        "moveInTypeCode": "MV001",
        "moveInTypeName": "즉시입주",
        "moveInDiscussionPossibleYN": "협의가능",
        "moveInPossibleYmd": "NOW",
        "monthlyManagementCost": 0,
        "articleFeatureDescription": "급매／명도비포함／진입도로대지포함／미래가치좋은",
        "detailDescription": "A.=-=-= ★맨투맨 공인중개사사무소★ =-=-= 매물번호↑↑↑\r\n\r\n＃친절함＃으로 마중하고\r\n＃전문적＃으로 중개하여\r\n＃만족감＃으로 배웅하는\r\n꼭 필요한 사람이 되겠습니다.\r\n\r\n☎카톡＆문자 문의 환영☎\r\n☎주저마시고 편하게 전화주세요☎\r\n\r\n▣ 매물 정보 ▣\r\n\r\n▷위치 \r\n -선정릉역 도보 5분 최상급지\r\n\r\n▷실면적  \r\n -대지 약 203평(건물주 제공)\r\n -연면적 약 435평(건물주 제공)\r\n\r\n▷금액\r\n -진입로대지,명도비포함: 165억\r\n\r\n▷주차  \r\n -15대 이상 가능\r\n\r\n▣ 매물 특징 ▣\r\n\r\n◎인근 지역 중 가장 상단에 있는 최상급지\r\n\r\n◎민간임대사업자 의무기간종료\r\n\r\n◎내부 리모델링후 수익형 부동산 추천\r\n\r\n◎지가상승으로 인한 미래가치 충분\r\n\r\n# 이외에도 다양한 매물보유\r\n# 금액 및 렌트프리 협의 최대한 노력하겠습니다\r\n# 손님에게 필요한 매물 무조건 찾아드립니다.편하게 전화 주세요:)\r\n━━━━━━━━━━━━━━━━━━━━━━\r\nㅇ M2M은 강남,강동,송파 등 서울 및 수도권 전역 다수의 물권을 확보하고 있습니다.\r\nㅇ M2M은 철저한 상권분석과 차별화된 ONE-STOP 서비스를 제공합니다.\r\n( 컨설팅, 인테리어, 광고미디어, 대출 상담가능)",
        "parkingCount": 12,
        "parkingPossibleYN": "Y",
        "duplexYN": "N",
        "floorLayerName": "단층",
        "hasBuildingUnitInfo": False,
        "lawUsage": "공동주택",
        "tagList": ["15년이내", "역세권", "급매", "방한개"],
        "isInterest": False,
        "isFalseHoodDeclared": False,
        "kisoConnectionYN": "Y",
        "detailAddressYn": "N",
        "isComplex": False,
        "isOwnerTradeCompleted": False,
    },
    "addition": {
        "articleNo": "2320636507",
        "articleName": "상가주택",
        "articleStatus": "R0",
        "realEstateTypeCode": "SGJT",
        "realEstateTypeName": "상가주택",
        "articleRealEstateTypeCode": "C03",
        "articleRealEstateTypeName": "상가주택",
        "tradeTypeCode": "A1",
        "tradeTypeName": "매매",
        "verificationTypeCode": "OWNER",
        "floorInfo": "4/B2",
        "priceChangeState": "SAME",
        "isPriceModification": False,
        "dealOrWarrantPrc": "165억",
        "area1": 486,
        "area2": 1434,
        "direction": "북향",
        "articleConfirmYmd": "20230515",
        "siteImageCount": 0,
        "articleFeatureDesc": "급매／명도비포함／진입도로대지포함／미래가치좋은",
        "tagList": ["15년이내", "역세권", "급매", "방한개"],
        "sameAddrCnt": 1,
        "sameAddrDirectCnt": 0,
        "sameAddrMaxPrc": "165억",
        "sameAddrMinPrc": "165억",
        "cpid": "SERVE",
        "cpName": "부동산써브",
        "cpPcArticleLinkUseAtArticleTitleYn": False,
        "cpPcArticleLinkUseAtCpNameYn": False,
        "cpMobileArticleLinkUseAtArticleTitleYn": False,
        "cpMobileArticleLinkUseAtCpNameYn": False,
        "latitude": "37.512631",
        "longitude": "127.040886",
        "isLocationShow": False,
        "realtorName": "맨투맨공인중개사사무소",
        "realtorId": "man2man712",
        "tradeCheckedByOwner": False,
        "isDirectTrade": False,
        "isInterest": False,
        "isComplex": False,
    },
    "noneHscp": {},
    "space": {
        "supplySpace": 0,
        "exclusiveSpace": 0,
        "groundSpace": 486.1,
        "totalSpace": 1434.82,
        "buildingSpace": 0,
        "expectSpace": 0,
        "groundShareSpace": 0,
        "exclusiveRate": "-",
    },
    "facility": {
        "directionTypeCode": "NN",
        "directionTypeName": "북향",
        "directionBaseTypeCode": "LVRM",
        "directionBaseTypeName": "거실 기준",
        "buildingUseAprvYmd": "20120809",
        "floorAreaRatio": "295.2",
        "buildingCoverageRatio": "-",
    },
    "floor": {
        "totalFloorCount": "-",
        "undergroundFloorCount": "B2",
        "uppergroundFloorCount": "4",
        "floorTypeCode": "00",
        "floorInputMethodCode": "00",
        "correspondingFloorCount": "-",
    },
    "price": {
        "rentPrice": 0,
        "dealPrice": 1650000,
        "warrantPrice": 0,
        "allWarrantPrice": 0,
        "financeTypeCode": "10",
        "financePrice": 200000,
        "premiumPrice": 0,
        "isalePrice": 0,
        "allRentPrice": 0,
        "priceBySpace": 0,
        "bondPrice": 0,
        "middlePayment": 0,
    },
    "ground": {},
    "rebuild": {},
    "oneroom": {},
    "redevelop": {},
    "buildingRegister": {
        "mgmBldrgstPk": "11680-7376",
        "regstrGbCdNm": "일반",
        "regstrKindCdNm": "일반건축물",
        "bylotCnt": 0,
        "mainAtchGbCdNm": "주건축물",
        "platArea": 0,
        "archArea": 177.16,
        "bcRat": 0,
        "totArea": 323.34,
        "vlRatEstmTotArea": 252.3,
        "vlRat": 0,
        "strctCdNm": "벽돌구조",
        "mainPurpsCdNm": "단독주택",
        "hhldCnt": 0,
        "fmlyCnt": 1,
        "allHoCnt": 1,
        "generationUnit": "가구",
        "grndFlrCnt": 2,
        "ugrndFlrCnt": 1,
        "rideUseElvtCnt": 0,
        "emgenUseElvtCnt": 0,
        "totalElvtCnt": 0,
        "elvtInfo": "",
        "atchBldCnt": 1,
        "totDongTotArea": 323.34,
        "indrMechUtcnt": 0,
        "oudrMechUtcnt": 0,
        "indrAutoUtcnt": 0,
        "oudrAutoUtcnt": 0,
        "etcParkInfo": "",
        "totalParkingCnt": 0,
        "useAprDay": "1980.12",
        "engrRat": 0,
        "engrEpi": 0,
        "gnBldCert": 0,
        "itgBldCert": 0,
        "bldX": 959449.47393759,
        "bldY": 1945988.08320399,
        "jiyukNm": "제1종일반주거지역",
        "jiyukNmLink": "https://terms.naver.com/entry.naver?docId=6411930&cid=42094&categoryId=42094",
        "jiyukCount": 2,
        "jiguNmLink": "",
        "jiguCount": 0,
        "guyukNmLink": "",
        "guyukCount": 0,
        "naid": "1168041663560100003700000",
        "pnu": "1168010800102650021",
        "bsource": "010101",
        "serviceYn": "Y",
        "hoCnt": 0,
        "exposureBldName": False,
    },
    "articlePhotos": [
        {
            "imageKey": "2320636507",
            "imageSrc": "/20230515_265/land_naver_1684125782587XHnKJ_JPEG/14095843_2023513171211.jpg",
            "imageType": "10",
            "imageId": "2320636507@20230515133917152417",
            "realtorName": "맨투맨공인중개사사무소",
            "smallCategoryName": "",
            "registYmdt": "20230515133917",
            "imageOrder": 5,
        },
        {
            "imageKey": "2320636507",
            "imageSrc": "/20230515_141/land_naver_16841257825898X8aI_JPEG/14095843_2023513171217.jpg",
            "imageType": "10",
            "imageId": "2320636507@20230515133917794868",
            "realtorName": "맨투맨공인중개사사무소",
            "smallCategoryName": "",
            "registYmdt": "20230515133917",
            "imageOrder": 5,
        },
        {
            "imageKey": "2320636507",
            "imageSrc": "/20230515_260/land_naver_1684125782593NuAGB_JPEG/14095843_2023513171234.jpg",
            "imageType": "10",
            "imageId": "2320636507@20230515133917799697",
            "realtorName": "맨투맨공인중개사사무소",
            "smallCategoryName": "",
            "registYmdt": "20230515133917",
            "imageOrder": 5,
        },
    ],
    "marketPrice": {},
    "articleTax": {
        "acquisitionTax": 495000000,
        "registTax": 0,
        "registFee": 723,
        "brokerFee": 115500000,
        "maxBrokerFee": 0.7,
        "eduTax": 49500000,
        "specialTax": 0,
        "registApplyFee": 0,
        "digitalRevenuStamp": 0,
        "nationHouseBond": 0,
        "totalPrice": 544500000,
    },
    "landPrice": {
        "hscpNo": "",
        "hscpType": "",
        "hscpNm": "",
        "bildNo": "",
        "dongNm": "",
        "hoNm": "",
        "hoFloor": "0",
        "lineNo": "",
        "pilotiYn": "",
        "existHo": "",
        "price": "0",
        "prevPrice": "0",
        "ptpNo": "",
        "supplyArea": "0",
        "totalArea": "0",
        "stdYear": 0,
        "stdYmd": 0,
    },
    "tabCategory": "",
    "schools": [],
    "realtor": {
        "realtorId": "man2man712",
        "realtorName": "맨투맨공인중개사사무소",
        "representativeName": "임경업",
        "address": "서울특별시 강동구 양재대로151길 18 라온 (명일동)",
        "establishRegistrationNo": "11740-2022-00099",
        "interlockId": "w44bhx",
        "representativeTelNo": "02-3428-4984",
        "cellPhoneNo": "010-8423-0547",
        "isCellPhoneExposure": True,
        "isRepresentativeTelExposure": True,
        "exposeTelTypeCode": "ALL",
    },
    "location": {"cityName": "서울시", "divisionName": "강남구", "sectionName": "논현동", "detailAddress": "서울시 강남구 논현동 265-10"},
    "isValidArticle": True,
    "maintenanceCost": {},
    "articleTitle": "상가주택",
    "articleSubTitle": "",
    "articleHeaderSubTitle": "상가주택",
    "dealerTelInfo": {
        "dealerNm": "맨투맨공인중개사사무소",
        "addr": "서울특별시 강동구 양재대로151길 18 라온 (명일동)",
        "expsTelTpCd": "ALL",
        "tradTpNm": "매매",
        "atclNm": "상가주택 상가주택",
        "atclStatCd": "R0",
        "bildNm": "상가주택",
        "atclNo": "2320636507",
        "prcInfo": "1650000",
        "leasePrc": "165억",
        "repTelNo": "02-3428-4984",
        "cellPhoneNo": "010-8423-0547",
        "phoneNoForSMS": "010-8423-0547",
    },
}
