{
    "user": {
        "isLogin": False,
        "isLandApp": False,
        "isAdmin": False,
        "isGroupId": False,
        "userNickName": False,
        "userOld": False,
        "connectTime": 1684818833535,
    },
    "deepLink": {"zoom": 0, "centerLat": 0, "centerLon": 0, "articleNoDeepLink": ""},
    "article": {
        "article": {
            "articleNo": "2320930153",
            "articleName": "한옥주택",
            "articleSubName": "",
            "cpId": "fine",
            "cortarNo": "1123010300",
            "tradeBuildingTypeCode": "BILD",
            "exposeStartYMD": "20230516",
            "exposeEndYMD": "20230615",
            "articleConfirmYMD": "20230516",
            "tradeCompleteYN": "N",
            "totalDongCount": 0,
            "buildingTypeName": "한옥주택",
            "articleStatusCode": "R0",
            "articleTypeCode": "C06",
            "realestateTypeCode": "HOJT",
            "realestateTypeName": "한옥주택",
            "tradeTypeCode": "A1",
            "tradeTypeName": "매매",
            "verificationTypeCode": "DOC",
            "applyYN": "N",
            "directTradeYN": "N",
            "mapLocationIndicationYn": "Y",
            "latitude": "37.5849606",
            "longitude": "127.0392593",
            "pnu": "1123010300106900002",
            "cityNo": "1100000000",
            "cityName": "서울시",
            "divisionName": "동대문구",
            "sectionName": "제기동",
            "realtorId": "9602220s",
            "walkingTimeToNearSubway": 10,
            "grandPlanList": [],
            "detailAddress": "",
            "jibunAddress": "690-2",
            "jibunAddressExposureYn": "N",
            "exposureAddress": "서울시 동대문구 제기동",
            "virtualAddressYn": "N",
            "roomCount": "5",
            "bathroomCount": "2",
            "moveInTypeCode": "MV001",
            "moveInTypeName": "즉시입주",
            "moveInPossibleYmd": "NOW",
            "monthlyManagementCost": 0,
            "buildingTypeCode": "C0602",
            "articleFeatureDescription": "주인 거주 가능한 한옥. 점포 2개 임대 중",
            "detailDescription": "깡통시장  근처 한옥\r\n길 가 점포 2개 500/89 임대 중",
            "parkingCount": 0,
            "parkingPossibleYN": "N",
            "duplexYN": "N",
            "floorLayerName": "단층",
            "hasBuildingUnitInfo": False,
            "lawUsage": "단독주택",
            "tagList": ["25년이상"],
            "isInterest": False,
            "isFalseHoodDeclared": False,
            "kisoConnectionYN": "Y",
            "detailAddressYn": "N",
            "isComplex": False,
            "isOwnerTradeCompleted": False,
        },
        "addition": {
            "articleNo": "2320930153",
            "articleName": "한옥주택",
            "articleStatus": "R0",
            "realEstateTypeCode": "HOJT",
            "realEstateTypeName": "한옥주택",
            "articleRealEstateTypeCode": "C03",
            "articleRealEstateTypeName": "한옥주택",
            "tradeTypeCode": "A1",
            "tradeTypeName": "매매",
            "verificationTypeCode": "DOC",
            "floorInfo": "1/-",
            "priceChangeState": "SAME",
            "isPriceModification": False,
            "dealOrWarrantPrc": "15억",
            "area1": 146,
            "area2": 82,
            "direction": "",
            "articleConfirmYmd": "20230516",
            "siteImageCount": 0,
            "articleFeatureDesc": "주인 거주 가능한 한옥. 점포 2개 임대 중",
            "tagList": ["25년이상"],
            "sameAddrCnt": 1,
            "sameAddrDirectCnt": 0,
            "sameAddrMaxPrc": "15억",
            "sameAddrMinPrc": "15억",
            "cpid": "fine",
            "cpName": "부동산포스",
            "cpPcArticleLinkUseAtArticleTitleYn": False,
            "cpPcArticleLinkUseAtCpNameYn": False,
            "cpMobileArticleLinkUseAtArticleTitleYn": False,
            "cpMobileArticleLinkUseAtCpNameYn": False,
            "latitude": "37.584961",
            "longitude": "127.039259",
            "isLocationShow": False,
            "realtorName": "성원공인중개사사무소",
            "realtorId": "9602220s",
            "tradeCheckedByOwner": False,
            "isDirectTrade": False,
            "isInterest": False,
            "isComplex": False,
        },
        "noneHscp": {},
        "space": {
            "supplySpace": 0,
            "exclusiveSpace": 0,
            "groundSpace": 146.2,
            "totalSpace": 82.28,
            "buildingSpace": 0,
            "expectSpace": 0,
            "groundShareSpace": 0,
            "exclusiveRate": "-",
        },
        "facility": {
            "directionTypeCode": "WW",
            "directionTypeName": "서향",
            "directionBaseTypeCode": "LVRM",
            "directionBaseTypeName": "거실 기준",
            "buildingUseAprvYmd": "19630831",
            "buildingUseAprvTypeCode": "CDY01",
            "buildingUseAprvTypeName": "사용승인일",
            "heatMethodTypeCode": "HT001",
            "heatMethodTypeName": "개별난방",
            "heatFuelTypeCode": "HF001",
            "heatFuelTypeName": "도시가스",
            "lifeFacilityList": "LF016",
            "lifeFacilities": ["샤워부스"],
            "floorAreaRatio": "56.3",
            "buildingCoverageRatio": "-",
        },
        "floor": {
            "totalFloorCount": "-",
            "undergroundFloorCount": "-",
            "uppergroundFloorCount": "1",
            "floorTypeCode": "00",
            "floorInputMethodCode": "00",
            "correspondingFloorCount": "-",
        },
        "price": {
            "rentPrice": 0,
            "dealPrice": 150000,
            "warrantPrice": 0,
            "allWarrantPrice": 500,
            "financeTypeCode": "00",
            "financePrice": 0,
            "premiumPrice": 0,
            "isalePrice": 0,
            "allRentPrice": 80,
            "priceBySpace": 3391,
            "bondPrice": 0,
            "middlePayment": 0,
        },
        "ground": {},
        "rebuild": {},
        "oneroom": {},
        "redevelop": {},
        "buildingRegister": {
            "mgmBldrgstPk": "11230-1846",
            "regstrGbCdNm": "일반",
            "regstrKindCdNm": "일반건축물",
            "bylotCnt": 0,
            "mainAtchGbCdNm": "주건축물",
            "platArea": 0,
            "archArea": 0,
            "bcRat": 0,
            "totArea": 82.28,
            "vlRatEstmTotArea": 0,
            "vlRat": 0,
            "strctCdNm": "일반목구조",
            "mainPurpsCdNm": "단독주택",
            "hhldCnt": 0,
            "fmlyCnt": 1,
            "allHoCnt": 1,
            "generationUnit": "가구",
            "grndFlrCnt": 1,
            "ugrndFlrCnt": 0,
            "rideUseElvtCnt": 0,
            "emgenUseElvtCnt": 0,
            "totalElvtCnt": 0,
            "elvtInfo": "",
            "atchBldCnt": 0,
            "totDongTotArea": 82.28,
            "indrMechUtcnt": 0,
            "oudrMechUtcnt": 0,
            "indrAutoUtcnt": 0,
            "oudrAutoUtcnt": 0,
            "etcParkInfo": "",
            "totalParkingCnt": 0,
            "useAprDay": "1963.08",
            "engrRat": 0,
            "engrEpi": 0,
            "gnBldCert": 0,
            "itgBldCert": 0,
            "bldX": 959319.83528561,
            "bldY": 1954051.30290316,
            "jiyukNm": "제2종일반주거지역",
            "jiyukNmLink": "https://terms.naver.com/entry.naver?docId=6411946&cid=42094&categoryId=42094",
            "jiyukCount": 2,
            "jiguNmLink": "",
            "jiguCount": 0,
            "guyukNmLink": "",
            "guyukCount": 0,
            "naid": "1123041152430100004200000",
            "pnu": "1123010300106900002",
            "bsource": "010101",
            "serviceYn": "Y",
            "hoCnt": 0,
            "exposureBldName": False,
        },
        "articlePhotos": [],
        "marketPrice": {},
        "articleTax": {
            "acquisitionTax": 45000000,
            "registTax": 0,
            "registFee": 118,
            "brokerFee": 10500000,
            "maxBrokerFee": 0.7,
            "eduTax": 4500000,
            "specialTax": 0,
            "registApplyFee": 0,
            "digitalRevenuStamp": 0,
            "nationHouseBond": 0,
            "totalPrice": 49500000,
        },
        "landPrice": {
            "hscpNo": "",
            "hscpType": "",
            "hscpNm": "",
            "bildNo": "",
            "dongNm": "",
            "hoNm": "",
            "hoFloor": "0",
            "lineNo": "",
            "pilotiYn": "",
            "existHo": "",
            "price": "0",
            "prevPrice": "0",
            "ptpNo": "",
            "supplyArea": "0",
            "totalArea": "0",
            "stdYear": 0,
            "stdYmd": 0,
        },
        "tabCategory": "",
        "schools": [],
        "realtor": {
            "realtorId": "9602220s",
            "realtorName": "성원공인중개사사무소",
            "representativeName": "홍성욱",
            "address": "서울특별시 동대문구 제기동 698 1층",
            "establishRegistrationNo": "11230-2021-00014",
            "representativeTelNo": "02-960-2220",
            "cellPhoneNo": "010-9687-9200",
            "isRepresentativeTelExposure": True,
            "exposeTelTypeCode": "ALL",
        },
        "location": {"cityName": "서울시", "divisionName": "동대문구", "sectionName": "제기동", "detailAddress": "서울시 동대문구 제기동"},
        "isValidArticle": True,
        "maintenanceCost": {},
        "articleTitle": "한옥주택",
        "articleSubTitle": "",
        "articleHeaderSubTitle": "한옥주택",
        "dealerTelInfo": {
            "dealerNm": "성원공인중개사사무소",
            "addr": "서울특별시 동대문구 제기동 698 1층",
            "expsTelTpCd": "ALL",
            "tradTpNm": "매매",
            "atclNm": "한옥주택 한옥주택",
            "atclStatCd": "R0",
            "bildNm": "한옥주택",
            "atclNo": "2320930153",
            "prcInfo": "150000",
            "leasePrc": "15억",
            "repTelNo": "02-960-2220",
            "cellPhoneNo": "010-9687-9200",
            "phoneNoForSMS": "010-9687-9200",
        },
    },
    "header": {"subName": "한옥주택", "isSubHeaderToolHidden": True},
    "transactionPrice": {
        "hscpNo": None,
        "ptpNo": None,
        "dealTransactionPrice": {"tradeType": "A1", "hasMore": None, "basisYearMonth": None, "list": []},
        "leaseTransactionPrice": {"tradeType": "B1", "hasMore": None, "basisYearMonth": None, "list": []},
        "rentTransactionPrice": {"tradeType": "B2", "hasMore": None, "basisYearMonth": None, "list": []},
    },
    "articleFacilities": {
        "nearBusRoute": [],
        "busCount": 0,
        "nearSubwayRoute": [],
        "subwayCount": 0,
        "nearFacility": [],
        "hotPlaceList": [],
        "complexFacility": [],
        "complexReport": {},
    },
    "aside": {
        "opened": False,
        "userId": None,
        "userNickName": None,
        "userEmail": None,
        "notificationCount": None,
        "interestAreaCount": None,
        "interestComplexCount": None,
        "interestArticleCount": None,
        "myhouseCount": None,
    },
    "notification": {"modifyResponse": None, "errorCode": None, "errorCount": 0},
    "modal": {"modalType": "", "className": "", "message": None},
    "interest": {"isInterest": None, "errorCode": None, "errorCount": 0},
    "apply": {"resultCode": 0, "apId": 0, "expectGuaranteeInfo": {}, "error": {"code": "", "message": ""}},
    "aroundStationDevelopmentPlan": [],
    "aroundJiguDevelopmentPlan": [],
    "complexInnerFacility": {"focused": False},
    "mediaViewer": {"index": -1, "mediaType": "NONE"},
    "banner": {"homeBanner": {}},
    "articleScroll": {"height": "initial"},
    "myHouse": {
        "myHouseList": [],
        "editedMyHouseList": [],
        "realPriceInfo": {"exposeRealPrice": False},
        "realPriceTable": {"realPrices": [], "realPriceBasisDate": "", "averageMonth": 0, "averagePrice": 0},
        "priceInfo": {
            "deal": {
                "upper": 0,
                "lower": 0,
                "deposit": 0,
                "leasePerDealRate": "",
                "baseDate": "",
                "cpName": "",
                "exposeInfo": False,
            },
            "lease": {
                "upper": 0,
                "lower": 0,
                "deposit": 0,
                "leasePerDealRate": "",
                "baseDate": "",
                "cpName": "",
                "exposeInfo": False,
            },
            "rent": {
                "upper": 0,
                "lower": 0,
                "deposit": 0,
                "leasePerDealRate": "",
                "baseDate": "",
                "cpName": "",
                "exposeInfo": False,
            },
        },
        "priceChart": {
            "isExposeChart": False,
            "floorList": [],
            "realPriceDataXList": [],
            "realPriceDataYList": [],
            "marketPriceXList": [],
            "upperMarketPriceYList": [],
            "lowerMarketPriceYList": [],
            "minAxisY": 0,
            "maxAxisY": 0,
            "gridYLines": [],
            "axisYTickValues": [],
        },
        "articles": {"totalCount": 0, "articleList": []},
        "myHouseRegisterInfo": {
            "myHouseRegisterStatusType": "",
            "myHouseNo": "",
            "tradeTpCd": "",
            "trendPriceExist": False,
        },
    },
    "searchAddress": {
        "query": "",
        "deliveryAddressList": [],
        "searchAddressList": None,
        "searchComplexList": None,
        "addressList": [],
        "buildingList": [],
        "buildingLoad": False,
        "hoList": [],
        "hoLoad": False,
        "pyeongList": [],
        "pyeongLoad": False,
        "exposureArea": None,
        "abbreviationAddress": None,
        "baseAddress": None,
        "cortarNo": None,
        "complexNo": None,
        "complexName": None,
        "realestateTypeCode": None,
        "realestateTypeName": None,
        "buildingName": None,
        "buildingNo": None,
        "hoName": None,
        "hoNo": None,
        "deliveryBuildingName": None,
        "deliveryHoName": None,
    },
    "myHouseRegister": {
        "success": False,
        "page": None,
        "myHouseNo": None,
        "baseAddress": None,
        "abbreviationAddress": None,
        "exposureArea": None,
        "cortarNo": None,
        "complexNo": None,
        "complexName": None,
        "buildingNo": None,
        "buildingName": None,
        "hoNo": None,
        "hoName": None,
        "pyeongNo": None,
        "pyeongName": None,
        "realestateTypeCode": None,
        "tradeTypeCode": None,
        "dealAmount": None,
        "warrantyAmount": None,
        "rentAmount": None,
        "tradeDate": None,
        "agreePrivacyCollectUsage": False,
        "agreePrivacyDisclosure": False,
    },
    "myHousePrivacy": {"agreePrivacyCollectUsage": None, "agreePrivacyDisclosure": None},
}
