{
    "article": {
        "articleNo": "2321821077",
        "articleName": "대형사무실",
        "articleSubName": "",
        "cpId": "hkdotcom",
        "cortarNo": "1168010500",
        "tradeBuildingTypeCode": "SPOFC",
        "exposeStartYMD": "20230522",
        "exposeEndYMD": "20230621",
        "articleConfirmYMD": "20230522",
        "tradeCompleteYN": "N",
        "totalDongCount": 0,
        "buildingTypeName": "대형사무실",
        "articleStatusCode": "R0",
        "articleTypeCode": "D01",
        "realestateTypeCode": "SMS",
        "realestateTypeName": "사무실",
        "tradeTypeCode": "A1",
        "tradeTypeName": "매매",
        "verificationTypeCode": "NDOC1",
        "verificationTypeName": "소유자",
        "applyYN": "N",
        "directTradeYN": "N",
        "mapLocationIndicationYn": "Y",
        "latitude": "37.5077769",
        "longitude": "127.0566318",
        "pnu": "1168010500101570003",
        "cityNo": "1100000000",
        "cityName": "서울시",
        "divisionName": "강남구",
        "sectionName": "삼성동",
        "walkingTimeToNearSubway": 9,
        "grandPlanList": [],
        "detailAddress": "",
        "jibunAddress": "157-3",
        "etcAddress": "엘지트윈텔2 4층412호",
        "exposureAddress": "서울시 강남구 삼성동",
        "virtualAddressYn": "N",
        "roomCount": "",
        "bathroomCount": "-",
        "moveInTypeCode": "MV001",
        "moveInTypeName": "즉시입주",
        "moveInDiscussionPossibleYN": "협의가능",
        "moveInPossibleYmd": "NOW",
        "buildingTypeCode": "D0101",
        "articleFeatureDescription": "급매 포스코사거리 대로변접함 구분건물 구분사무실매매",
        "detailDescription": "급매 테헤란로 포스코사거리 대로변접한 구분건물 매매물건입니다\n삼성역과 삼성중앙역을 도보로 이용 가능한 역세권 빌딩입니다\n공급면적 48.4평이고 전용면적 23.9평입니다\n대지지분은 3.02평입니다\n매매금액은 9억6천만원입니다\n2년전 올수리 리모델링한 깨끗한 사무실(업무시설)입니다\n전망뷰 와 근무환경 뛰어나고 교통이 편리합니다\n삼성역 코엑스 블록으로 향후 투자가치 매우 높습니다\n전화주시면 친절하게 안내해 드리겠습니다",
        "parkingCount": 79,
        "parkingPossibleYN": "Y",
        "duplexYN": "N",
        "floorLayerName": "단층",
        "hasBuildingUnitInfo": False,
        "lawUsage": "업무시설",
        "tagList": ["25년이내", "급매", "지상층(1층제외)", "주차가능"],
        "isInterest": False,
        "isFalseHoodDeclared": False,
        "kisoConnectionYN": "Y",
        "detailAddressYn": "N",
        "isComplex": False,
        "isOwnerTradeCompleted": False,
    },
    "addition": {
        "articleNo": "2321821077",
        "articleName": "대형사무실",
        "articleStatus": "R0",
        "realEstateTypeCode": "SMS",
        "realEstateTypeName": "사무실",
        "articleRealEstateTypeCode": "D01",
        "articleRealEstateTypeName": "사무실",
        "tradeTypeCode": "A1",
        "tradeTypeName": "매매",
        "verificationTypeCode": "NDOC1",
        "floorInfo": "4/19",
        "priceChangeState": "SAME",
        "isPriceModification": False,
        "dealOrWarrantPrc": "9억 6,000",
        "area1": 160,
        "area2": 79,
        "direction": "남향",
        "articleConfirmYmd": "20230522",
        "siteImageCount": 0,
        "articleFeatureDesc": "급매 포스코사거리 대로변접함 구분건물 구분사무실매매",
        "tagList": ["25년이내", "급매", "지상층(1층제외)", "주차가능"],
        "sameAddrCnt": 1,
        "sameAddrDirectCnt": 0,
        "sameAddrMaxPrc": "9억 6,000",
        "sameAddrMinPrc": "9억 6,000",
        "cpid": "hkdotcom",
        "cpName": "한경부동산",
        "cpPcArticleLinkUseAtArticleTitleYn": False,
        "cpPcArticleLinkUseAtCpNameYn": False,
        "cpMobileArticleLinkUseAtArticleTitleYn": False,
        "cpMobileArticleLinkUseAtCpNameYn": False,
        "latitude": "37.507777",
        "longitude": "127.056632",
        "isLocationShow": False,
        "realtorName": "강남공인중개사사무소",
        "tradeCheckedByOwner": False,
        "isDirectTrade": False,
        "isInterest": False,
        "isComplex": False,
    },
    "noneHscp": {},
    "space": {
        "supplySpace": 160.23,
        "exclusiveSpace": 79.03,
        "groundSpace": 0,
        "totalSpace": 0,
        "buildingSpace": 0,
        "expectSpace": 0,
        "groundShareSpace": 0,
        "exclusiveRate": "49",
    },
    "facility": {
        "directionTypeCode": "SS",
        "directionTypeName": "남향",
        "buildingUseAprvYmd": "20000526",
        "buildingUseAprvTypeCode": "CDY01",
        "buildingUseAprvTypeName": "사용승인일",
        "floorAreaRatio": "-",
        "buildingCoverageRatio": "-",
    },
    "floor": {
        "totalFloorCount": "19",
        "undergroundFloorCount": "-",
        "uppergroundFloorCount": "-",
        "floorTypeCode": "00",
        "floorInputMethodCode": "00",
        "correspondingFloorCount": "4",
    },
    "price": {
        "rentPrice": 0,
        "dealPrice": 96000,
        "warrantPrice": 0,
        "allWarrantPrice": 0,
        "financeTypeCode": "00",
        "financePrice": 0,
        "premiumPrice": 0,
        "isalePrice": 0,
        "allRentPrice": 0,
        "priceBySpace": 1981,
        "bondPrice": 0,
        "middlePayment": 0,
    },
    "ground": {},
    "rebuild": {},
    "oneroom": {},
    "redevelop": {},
    "buildingRegister": {},
    "articlePhotos": [],
    "marketPrice": {},
    "articleTax": {
        "acquisitionTax": 38400000,
        "registTax": 0,
        "registFee": 90,
        "brokerFee": 8640000,
        "maxBrokerFee": 0.9,
        "eduTax": 3840000,
        "specialTax": 1920000,
        "registApplyFee": 0,
        "digitalRevenuStamp": 0,
        "nationHouseBond": 0,
        "totalPrice": 44160000,
    },
    "landPrice": {
        "hscpNo": "",
        "hscpType": "",
        "hscpNm": "",
        "bildNo": "",
        "dongNm": "",
        "hoNm": "",
        "hoFloor": "0",
        "lineNo": "",
        "pilotiYn": "",
        "existHo": "",
        "price": "0",
        "prevPrice": "0",
        "ptpNo": "",
        "supplyArea": "0",
        "totalArea": "0",
        "stdYear": 0,
        "stdYmd": 0,
    },
    "tabCategory": "",
    "schools": [],
    "realtor": {
        "realtorName": "강남공인중개사사무소",
        "representativeName": "문상모",
        "address": "서울특별시 강남구  대치동 890-54 5층504호",
        "establishRegistrationNo": "11680-2019-00495",
        "representativeTelNo": "010-7758-8034",
        "cellPhoneNo": "010-7758-8034",
        "exposeTelTypeCode": "ALL",
    },
    "location": {"cityName": "서울시", "divisionName": "강남구", "sectionName": "삼성동", "detailAddress": "서울시 강남구 삼성동"},
    "isValidArticle": True,
    "maintenanceCost": {},
    "articleTitle": "대형사무실",
    "articleSubTitle": "",
    "articleHeaderSubTitle": "대형사무실",
    "dealerTelInfo": {
        "dealerNm": "강남공인중개사사무소",
        "addr": "서울특별시 강남구  대치동 890-54 5층504호",
        "expsTelTpCd": "ALL",
        "tradTpNm": "매매",
        "atclNm": "대형사무실 대형사무실",
        "atclStatCd": "R0",
        "bildNm": "대형사무실",
        "atclNo": "2321821077",
        "prcInfo": "96000",
        "leasePrc": "9억 6,000",
        "repTelNo": "010-7758-8034",
        "cellPhoneNo": "010-7758-8034",
        "phoneNoForSMS": "010-7758-8034",
    },
}
