{
    "article": {
        "articleNo": "2320547010",
        "articleName": "답",
        "articleSubName": "",
        "cpId": "rter",
        "cortarNo": "4182031000",
        "tradeBuildingTypeCode": "GRND",
        "exposeStartYMD": "20230515",
        "exposeEndYMD": "20230614",
        "articleConfirmYMD": "20230515",
        "tradeCompleteYN": "N",
        "totalDongCount": 0,
        "buildingTypeName": "답",
        "articleStatusCode": "R0",
        "articleTypeCode": "E03",
        "realestateTypeCode": "TJ",
        "realestateTypeName": "토지",
        "tradeTypeCode": "A1",
        "tradeTypeName": "매매",
        "verificationTypeCode": "NDOC1",
        "verificationTypeName": "소유자",
        "applyYN": "N",
        "directTradeYN": "N",
        "mapLocationIndicationYn": "Y",
        "latitude": "37.6634031",
        "longitude": "127.4892803",
        "pnu": "4182031021102690001",
        "cityNo": "4100000000",
        "cityName": "경기도",
        "divisionName": "가평군",
        "sectionName": "설악면",
        "realtorId": "ok-realty",
        "walkingTimeToNearSubway": 0,
        "grandPlanList": [],
        "detailAddress": "",
        "liAddress": "신천리",
        "jibunAddress": "269-1",
        "etcAddress": "270-4번지 포함한 2필지 일괄매매",
        "exposureAddress": "경기도 가평군 설악면 신천리",
        "virtualAddressYn": "N",
        "roomCount": "",
        "bathroomCount": "-",
        "moveInTypeCode": "MV001",
        "moveInTypeName": "즉시입주",
        "monthlyManagementCost": 0,
        "buildingTypeCode": "E0302",
        "articleFeatureDescription": "소유주 직접 의뢰 설악IC인근 토지매매",
        "currentUsage": "나대지",
        "recommendUsage": "건축부지",
        "detailDescription": "주택 등 건물 신축에 편리하도록 성토한 토지매매입니다.\r\n\r\n\r\n인접토지 포함한 2필지 1,335평 일괄매매입니다.\r\n\r\n도로를 끼고 있어 차량진입이 편리합니다.\r\n\r\n\r\n필지분할 설계를 하였으며,\r\n\r\n550평에 대한 개발행위허가(단독주택 신축 및 부지조성)를 받았습니다.",
        "parkingCount": 0,
        "parkingPerHouseholdCount": "0",
        "parkingPossibleYN": "N",
        "duplexYN": "N",
        "floorLayerName": "단층",
        "hasBuildingUnitInfo": False,
        "tagList": [],
        "isInterest": False,
        "isFalseHoodDeclared": False,
        "kisoConnectionYN": "Y",
        "detailAddressYn": "N",
        "isComplex": False,
        "isOwnerTradeCompleted": False,
    },
    "addition": {
        "articleNo": "2320547010",
        "articleName": "답",
        "articleStatus": "R0",
        "realEstateTypeCode": "TJ",
        "realEstateTypeName": "토지",
        "articleRealEstateTypeCode": "E03",
        "articleRealEstateTypeName": "토지/임야",
        "tradeTypeCode": "A1",
        "tradeTypeName": "매매",
        "verificationTypeCode": "NDOC1",
        "floorInfo": "",
        "priceChangeState": "SAME",
        "isPriceModification": False,
        "dealOrWarrantPrc": "12억",
        "area1": 4414,
        "area2": 0,
        "articleConfirmYmd": "20230515",
        "siteImageCount": 0,
        "articleFeatureDesc": "소유주 직접 의뢰 설악IC인근 토지매매",
        "tagList": [],
        "sameAddrCnt": 1,
        "sameAddrDirectCnt": 0,
        "sameAddrMaxPrc": "12억",
        "sameAddrMinPrc": "12억",
        "cpid": "rter",
        "cpName": "알터",
        "cpPcArticleLinkUseAtArticleTitleYn": False,
        "cpPcArticleLinkUseAtCpNameYn": False,
        "cpMobileArticleLinkUseAtArticleTitleYn": False,
        "cpMobileArticleLinkUseAtCpNameYn": False,
        "latitude": "37.663403",
        "longitude": "127.48928",
        "isLocationShow": False,
        "realtorName": "OK부동산공인중개사사무소",
        "realtorId": "ok-realty",
        "tradeCheckedByOwner": False,
        "isDirectTrade": False,
        "isInterest": False,
        "isComplex": False,
    },
    "noneHscp": {},
    "space": {
        "supplySpace": 0,
        "exclusiveSpace": 0,
        "groundSpace": 4414,
        "totalSpace": 0,
        "buildingSpace": 0,
        "expectSpace": 0,
        "groundShareSpace": 0,
        "exclusiveRate": "-",
    },
    "facility": {"usageTypeCode": "62", "usageTypeName": "계획관리지역", "floorAreaRatio": "-", "buildingCoverageRatio": "-"},
    "floor": {
        "totalFloorCount": "-",
        "undergroundFloorCount": "-",
        "uppergroundFloorCount": "-",
        "floorTypeCode": "00",
        "floorInputMethodCode": "00",
        "correspondingFloorCount": "-",
    },
    "price": {
        "rentPrice": 0,
        "dealPrice": 120000,
        "warrantPrice": 0,
        "allWarrantPrice": 0,
        "financeTypeCode": "10",
        "financePrice": 0,
        "premiumPrice": 0,
        "isalePrice": 0,
        "allRentPrice": 0,
        "priceBySpace": 90,
        "bondPrice": 0,
        "middlePayment": 0,
    },
    "ground": {"usageAreaTypeName": "계획관리지역", "countryUsageYN": "Y", "roadYN": "Y"},
    "rebuild": {},
    "oneroom": {},
    "redevelop": {},
    "buildingRegister": {},
    "articlePhotos": [],
    "marketPrice": {},
    "articleTax": {
        "acquisitionTax": 36000000,
        "registTax": 0,
        "registFee": 103,
        "brokerFee": 10800000,
        "maxBrokerFee": 0.9,
        "eduTax": 2400000,
        "specialTax": 2400000,
        "registApplyFee": 0,
        "digitalRevenuStamp": 0,
        "nationHouseBond": 0,
        "totalPrice": 40800000,
    },
    "landPrice": {
        "hscpNo": "",
        "hscpType": "",
        "hscpNm": "",
        "bildNo": "",
        "dongNm": "",
        "hoNm": "",
        "hoFloor": "0",
        "lineNo": "",
        "pilotiYn": "",
        "existHo": "",
        "price": "0",
        "prevPrice": "0",
        "ptpNo": "",
        "supplyArea": "0",
        "totalArea": "0",
        "stdYear": 0,
        "stdYmd": 0,
    },
    "tabCategory": "",
    "schools": [],
    "realtor": {
        "realtorId": "ok-realty",
        "realtorName": "OK부동산공인중개사사무소",
        "representativeName": "신옥균",
        "address": "서울특별시 용산구 한강대로7길 18-10 1층",
        "establishRegistrationNo": "11170-2018-00165",
        "representativeTelNo": "02-790-3489",
        "cellPhoneNo": "010-5170-3489",
        "isCellPhoneExposure": True,
        "isRepresentativeTelExposure": True,
        "exposeTelTypeCode": "ALL",
    },
    "location": {"cityName": "경기도", "divisionName": "가평군", "sectionName": "설악면", "detailAddress": "경기도 가평군 설악면 신천리"},
    "isValidArticle": True,
    "maintenanceCost": {},
    "articleTitle": "답",
    "articleSubTitle": "",
    "articleHeaderSubTitle": "답",
    "dealerTelInfo": {
        "dealerNm": "OK부동산공인중개사사무소",
        "addr": "서울특별시 용산구 한강대로7길 18-10 1층",
        "expsTelTpCd": "ALL",
        "tradTpNm": "매매",
        "atclNm": "답 답",
        "atclStatCd": "R0",
        "bildNm": "답",
        "atclNo": "2320547010",
        "prcInfo": "120000",
        "leasePrc": "12억",
        "repTelNo": "02-790-3489",
        "cellPhoneNo": "010-5170-3489",
        "phoneNoForSMS": "010-5170-3489",
    },
}
