{
    "article": {
        "articleNo": "2320650126",
        "articleName": "전원주택",
        "articleSubName": "",
        "cpId": "bizmk",
        "cortarNo": "4182032500",
        "tradeBuildingTypeCode": "BILD",
        "exposeStartYMD": "20230515",
        "exposeEndYMD": "20230614",
        "articleConfirmYMD": "20230515",
        "tradeCompleteYN": "N",
        "totalDongCount": 0,
        "buildingTypeName": "전원주택",
        "articleStatusCode": "R0",
        "articleTypeCode": "C04",
        "realestateTypeCode": "JWJT",
        "realestateTypeName": "전원주택",
        "tradeTypeCode": "A1",
        "tradeTypeName": "매매",
        "verificationTypeCode": "OWNER",
        "verificationTypeName": "집주인",
        "applyYN": "N",
        "directTradeYN": "N",
        "mapLocationIndicationYn": "Y",
        "latitude": "37.7121421",
        "longitude": "127.5062945",
        "pnu": "4182032526103930023",
        "cityNo": "4100000000",
        "cityName": "경기도",
        "divisionName": "가평군",
        "sectionName": "청평면",
        "realtorId": "f9736611",
        "walkingTimeToNearSubway": 0,
        "grandPlanList": [],
        "detailAddress": "",
        "liAddress": "고성리",
        "jibunAddress": "393-23",
        "jibunAddressExposureYn": "N",
        "etcAddress": "1층 18호",
        "exposureAddress": "경기도 가평군 청평면 고성리",
        "virtualAddressYn": "N",
        "roomCount": "2",
        "bathroomCount": "2",
        "householdCount": "1",
        "moveInTypeCode": "MV001",
        "moveInTypeName": "즉시입주",
        "moveInDiscussionPossibleYN": "협의가능",
        "moveInPossibleYmd": "NOW",
        "monthlyManagementCost": 0,
        "buildingTypeCode": "C0401",
        "articleFeatureDescription": "설악IC에서 차량으로 8분",
        "detailDescription": "전망이 너무좋으며, 집이 아주튼튼하게 잘건축되어 있고 조용하고 아주 좋아요\r\n평소에 전원주택생활하고 싶으신분들은 서울에서 가깝고 공기좋고 텃밭도있고, 내부도 아주 깔끔합니다.",
        "parkingCount": 5,
        "parkingPossibleYN": "Y",
        "duplexYN": "N",
        "floorLayerName": "단층",
        "hasBuildingUnitInfo": False,
        "lawUsage": "단독주택",
        "tagList": ["10년이내", "테라스", "마당", "화장실두개"],
        "isInterest": False,
        "isFalseHoodDeclared": False,
        "kisoConnectionYN": "Y",
        "detailAddressYn": "N",
        "isComplex": False,
        "isOwnerTradeCompleted": False,
    },
    "addition": {
        "articleNo": "2320650126",
        "articleName": "전원주택",
        "articleStatus": "R0",
        "realEstateTypeCode": "JWJT",
        "realEstateTypeName": "전원주택",
        "articleRealEstateTypeCode": "C03",
        "articleRealEstateTypeName": "전원주택",
        "tradeTypeCode": "A1",
        "tradeTypeName": "매매",
        "verificationTypeCode": "OWNER",
        "floorInfo": "1/-",
        "priceChangeState": "SAME",
        "isPriceModification": False,
        "dealOrWarrantPrc": "3억 5,000",
        "area1": 562,
        "area2": 110,
        "direction": "남서향",
        "articleConfirmYmd": "20230515",
        "siteImageCount": 0,
        "articleFeatureDesc": "설악IC에서 차량으로 8분",
        "tagList": ["10년이내", "테라스", "마당", "화장실두개"],
        "sameAddrCnt": 1,
        "sameAddrDirectCnt": 0,
        "sameAddrMaxPrc": "3억 5,000",
        "sameAddrMinPrc": "3억 5,000",
        "cpid": "bizmk",
        "cpName": "매경부동산",
        "cpPcArticleLinkUseAtArticleTitleYn": False,
        "cpPcArticleLinkUseAtCpNameYn": False,
        "cpMobileArticleLinkUseAtArticleTitleYn": False,
        "cpMobileArticleLinkUseAtCpNameYn": False,
        "latitude": "37.712142",
        "longitude": "127.506295",
        "isLocationShow": False,
        "realtorName": "하나공인중개사사무소",
        "realtorId": "f9736611",
        "tradeCheckedByOwner": False,
        "isDirectTrade": False,
        "isInterest": False,
        "isComplex": False,
    },
    "noneHscp": {},
    "space": {
        "supplySpace": 0,
        "exclusiveSpace": 0,
        "groundSpace": 562,
        "totalSpace": 110.94,
        "buildingSpace": 110.94,
        "expectSpace": 0,
        "groundShareSpace": 0,
        "exclusiveRate": "-",
    },
    "facility": {
        "directionTypeCode": "WS",
        "directionTypeName": "남서향",
        "directionBaseTypeCode": "LVRM",
        "directionBaseTypeName": "거실 기준",
        "buildingUseAprvYmd": "20140314",
        "buildingUseAprvTypeCode": "CDY01",
        "buildingUseAprvTypeName": "사용승인일",
        "heatMethodTypeCode": "HT001",
        "heatMethodTypeName": "개별난방",
        "heatFuelTypeCode": "HF003",
        "heatFuelTypeName": "기름",
        "airconFacilityList": "AC001,AC002",
        "airconFacilities": ["벽걸이에어컨", "스탠드에어컨"],
        "lifeFacilityList": "LF003,LF006,LF001,LF002,LF005,LF007,LF009,LF010,LF016,LF015,LF014,LF008",
        "lifeFacilities": ["침대", "옷장", "붙박이장", "식탁", "소파", "신발장", "냉장고", "세탁기", "샤워부스", "싱크대", "가스레인지", "전자레인지"],
        "securityFacilityList": "SEC04",
        "securityFacilities": ["카드키"],
        "etcFacilityList": "ETC04,ETC05,ETC03",
        "etcFacilities": ["테라스", "마당", "베란다"],
        "floorAreaRatio": "19.7",
        "buildingCoverageRatio": "19.7",
        "facilityVeranda": "베란다",
    },
    "floor": {
        "totalFloorCount": "-",
        "undergroundFloorCount": "-",
        "uppergroundFloorCount": "1",
        "floorTypeCode": "00",
        "floorInputMethodCode": "00",
        "correspondingFloorCount": "-",
    },
    "price": {
        "rentPrice": 0,
        "dealPrice": 35000,
        "warrantPrice": 0,
        "allWarrantPrice": 0,
        "financeTypeCode": "00",
        "financePrice": 0,
        "premiumPrice": 0,
        "isalePrice": 0,
        "allRentPrice": 0,
        "priceBySpace": 206,
        "bondPrice": 0,
        "middlePayment": 0,
    },
    "ground": {},
    "rebuild": {},
    "oneroom": {},
    "redevelop": {},
    "buildingRegister": {
        "mgmBldrgstPk": "41820-100204105",
        "regstrGbCdNm": "일반",
        "regstrKindCdNm": "일반건축물",
        "bylotCnt": 0,
        "mainAtchGbCdNm": "주건축물",
        "platArea": 562,
        "archArea": 110.94,
        "bcRat": 19.74,
        "totArea": 110.94,
        "vlRatEstmTotArea": 110.94,
        "vlRat": 19.74,
        "strctCdNm": "철근콘크리트구조",
        "mainPurpsCdNm": "단독주택",
        "hhldCnt": 0,
        "fmlyCnt": 1,
        "allHoCnt": 1,
        "generationUnit": "가구",
        "grndFlrCnt": 1,
        "ugrndFlrCnt": 0,
        "rideUseElvtCnt": 0,
        "emgenUseElvtCnt": 0,
        "totalElvtCnt": 0,
        "elvtInfo": "",
        "atchBldCnt": 0,
        "totDongTotArea": 110.94,
        "indrMechUtcnt": 0,
        "oudrMechUtcnt": 0,
        "indrAutoUtcnt": 0,
        "oudrAutoUtcnt": 1,
        "etcParkInfo": "(옥외자주식:1)",
        "totalParkingCnt": 1,
        "useAprDay": "2013.07",
        "engrRat": 0,
        "engrEpi": 0,
        "gnBldCert": 0,
        "itgBldCert": 0,
        "bldX": 1000557.95582,
        "bldY": 1968063.38805,
        "jiyukNm": "계획관리지역",
        "jiyukNmLink": "https://terms.naver.com/entry.naver?docId=6413722&cid=42094&categoryId=42094",
        "jiyukCount": 2,
        "jiguNmLink": "",
        "jiguCount": 0,
        "guyukNmLink": "",
        "guyukCount": 0,
        "naid": "4182044480130100006700018",
        "pnu": "4182032526103930023",
        "bsource": "010102",
        "serviceYn": "Y",
        "hoCnt": 0,
        "exposureBldName": False,
    },
    "articlePhotos": [],
    "marketPrice": {},
    "articleTax": {
        "acquisitionTax": 3500000,
        "registTax": 0,
        "registFee": 52,
        "brokerFee": 1400000,
        "maxBrokerFee": 0.4,
        "eduTax": 350000,
        "specialTax": 0,
        "registApplyFee": 0,
        "digitalRevenuStamp": 0,
        "nationHouseBond": 0,
        "totalPrice": 3850000,
    },
    "landPrice": {
        "hscpNo": "",
        "hscpType": "",
        "hscpNm": "",
        "bildNo": "",
        "dongNm": "",
        "hoNm": "",
        "hoFloor": "0",
        "lineNo": "",
        "pilotiYn": "",
        "existHo": "",
        "price": "0",
        "prevPrice": "0",
        "ptpNo": "",
        "supplyArea": "0",
        "totalArea": "0",
        "stdYear": 0,
        "stdYmd": 0,
    },
    "tabCategory": "",
    "schools": [],
    "realtor": {
        "realtorId": "f9736611",
        "realtorName": "하나공인중개사사무소",
        "representativeName": "강정숙",
        "address": "서울 노원구 섬밭로 263,롯데아파트상가 1층 26호",
        "establishRegistrationNo": "92333000-05056",
        "profileImageUrl": "/20150106_74/rltr_profile_1420519444355N918i_JPEG/f9736611_cropImage.jpg",
        "profileFullImageUrl": "/20140619_157/rltr_profile_1403137404957EnGTp_JPEG/1403137404590_%B2%D9%B9%CC%B1%E2%C7%CF%B3%AA_%28%B3%EB%BF%F8_%C1%DF%B0%E8%29_%BB%E7%C1%F8.jpg",
        "representativeTelNo": "02-973-6611",
        "cellPhoneNo": "010-8949-7541",
        "isCellPhoneExposure": True,
        "isRepresentativeTelExposure": True,
        "exposeTelTypeCode": "ALL",
    },
    "location": {"cityName": "경기도", "divisionName": "가평군", "sectionName": "청평면", "detailAddress": "경기도 가평군 청평면 고성리"},
    "isValidArticle": True,
    "maintenanceCost": {},
    "articleTitle": "전원주택",
    "articleSubTitle": "",
    "articleHeaderSubTitle": "전원주택",
    "dealerTelInfo": {
        "dealerNm": "하나공인중개사사무소",
        "addr": "서울 노원구 섬밭로 263,롯데아파트상가 1층 26호",
        "expsTelTpCd": "ALL",
        "tradTpNm": "매매",
        "atclNm": "전원주택 전원주택",
        "atclStatCd": "R0",
        "bildNm": "전원주택",
        "atclNo": "2320650126",
        "prcInfo": "35000",
        "leasePrc": "3억 5,000",
        "repTelNo": "02-973-6611",
        "realtorRepImgPath": "/20150106_74/rltr_profile_1420519444355N918i_JPEG/f9736611_cropImage.jpg",
        "cellPhoneNo": "010-8949-7541",
        "phoneNoForSMS": "010-8949-7541",
    },
}
