{
    "article": {
        "articleNo": "2321886130",
        "articleName": "단독",
        "articleSubName": "",
        "cpId": "SERVE",
        "cortarNo": "4182032500",
        "tradeBuildingTypeCode": "BILD",
        "exposeStartYMD": "20230523",
        "exposeEndYMD": "20230622",
        "articleConfirmYMD": "20230523",
        "tradeCompleteYN": "N",
        "totalDongCount": 0,
        "buildingTypeName": "단독",
        "articleStatusCode": "R0",
        "articleTypeCode": "C03",
        "realestateTypeCode": "DDDGG",
        "realestateTypeName": "단독/다가구",
        "tradeTypeCode": "A1",
        "tradeTypeName": "매매",
        "verificationTypeCode": "DOC",
        "applyYN": "N",
        "directTradeYN": "N",
        "mapLocationIndicationYn": "Y",
        "latitude": "37.727559",
        "longitude": "127.4143433",
        "pnu": "4182032521107190000",
        "cityNo": "4100000000",
        "cityName": "경기도",
        "divisionName": "가평군",
        "sectionName": "청평면",
        "realtorId": "dbsgmlwjd082508",
        "walkingTimeToNearSubway": 0,
        "grandPlanList": [],
        "detailAddress": "",
        "liAddress": "청평리",
        "jibunAddress": "719",
        "jibunAddressExposureYn": "N",
        "etcAddress": "전체",
        "exposureAddress": "경기도 가평군 청평면 청평리",
        "virtualAddressYn": "N",
        "roomCount": "3",
        "bathroomCount": "1",
        "moveInTypeCode": "MV001",
        "moveInTypeName": "즉시입주",
        "moveInPossibleYmd": "NOW",
        "monthlyManagementCost": 0,
        "buildingTypeCode": "C0301",
        "articleFeatureDescription": "리모델링된 조용한 단독",
        "detailDescription": "*향후 전망되는 위치\r\n*조용히 단독주택 생활하실분\r\n*내부 리모델링되어 크게 손볼곳 없음\r\n*집보시고 결정하세요",
        "parkingCount": 1,
        "parkingPossibleYN": "Y",
        "duplexYN": "N",
        "floorLayerName": "단층",
        "hasBuildingUnitInfo": False,
        "lawUsage": "단독주택",
        "tagList": ["25년이상", "방세개", "화장실한개", "주차가능"],
        "isInterest": False,
        "isFalseHoodDeclared": False,
        "kisoConnectionYN": "Y",
        "detailAddressYn": "N",
        "isComplex": False,
        "isOwnerTradeCompleted": False,
    },
    "addition": {
        "articleNo": "2321886130",
        "articleName": "단독",
        "articleStatus": "R0",
        "realEstateTypeCode": "DDDGG",
        "realEstateTypeName": "단독/다가구",
        "articleRealEstateTypeCode": "C03",
        "articleRealEstateTypeName": "단독/다가구",
        "tradeTypeCode": "A1",
        "tradeTypeName": "매매",
        "verificationTypeCode": "DOC",
        "floorInfo": "1/-",
        "priceChangeState": "SAME",
        "isPriceModification": False,
        "dealOrWarrantPrc": "1억 6,500",
        "area1": 162,
        "area2": 64,
        "direction": "남동향",
        "articleConfirmYmd": "20230523",
        "siteImageCount": 0,
        "articleFeatureDesc": "리모델링된 조용한 단독",
        "tagList": ["25년이상", "방세개", "화장실한개", "주차가능"],
        "sameAddrCnt": 1,
        "sameAddrDirectCnt": 0,
        "sameAddrMaxPrc": "1억 6,500",
        "sameAddrMinPrc": "1억 6,500",
        "cpid": "SERVE",
        "cpName": "부동산써브",
        "cpPcArticleLinkUseAtArticleTitleYn": False,
        "cpPcArticleLinkUseAtCpNameYn": False,
        "cpMobileArticleLinkUseAtArticleTitleYn": False,
        "cpMobileArticleLinkUseAtCpNameYn": False,
        "latitude": "37.727559",
        "longitude": "127.414343",
        "isLocationShow": False,
        "realtorName": "청평만복부동산공인중개사사무소",
        "realtorId": "dbsgmlwjd082508",
        "tradeCheckedByOwner": False,
        "isDirectTrade": False,
        "isInterest": False,
        "isComplex": False,
    },
    "noneHscp": {},
    "space": {
        "supplySpace": 0,
        "exclusiveSpace": 0,
        "groundSpace": 162,
        "totalSpace": 64.8,
        "buildingSpace": 0,
        "expectSpace": 0,
        "groundShareSpace": 0,
        "exclusiveRate": "-",
    },
    "facility": {
        "directionTypeCode": "ES",
        "directionTypeName": "남동향",
        "directionBaseTypeCode": "LVRM",
        "directionBaseTypeName": "거실 기준",
        "buildingUseAprvYmd": "19861204",
        "heatMethodTypeCode": "HT001",
        "heatMethodTypeName": "개별난방",
        "heatFuelTypeCode": "HF001",
        "heatFuelTypeName": "도시가스",
        "floorAreaRatio": "40.0",
        "buildingCoverageRatio": "-",
    },
    "floor": {
        "totalFloorCount": "-",
        "undergroundFloorCount": "-",
        "uppergroundFloorCount": "1",
        "floorTypeCode": "00",
        "floorInputMethodCode": "00",
        "correspondingFloorCount": "-",
    },
    "price": {
        "rentPrice": 0,
        "dealPrice": 16500,
        "warrantPrice": 0,
        "allWarrantPrice": 0,
        "financeTypeCode": "00",
        "financePrice": 0,
        "premiumPrice": 0,
        "isalePrice": 0,
        "allRentPrice": 0,
        "priceBySpace": 337,
        "bondPrice": 0,
        "middlePayment": 0,
    },
    "ground": {},
    "rebuild": {},
    "oneroom": {},
    "redevelop": {},
    "buildingRegister": {
        "mgmBldrgstPk": "41820-10628",
        "regstrGbCdNm": "일반",
        "regstrKindCdNm": "일반건축물",
        "bylotCnt": 1,
        "mainAtchGbCdNm": "주건축물",
        "platArea": 0,
        "archArea": 64.8,
        "bcRat": 0,
        "totArea": 64.8,
        "vlRatEstmTotArea": 64.8,
        "vlRat": 0,
        "strctCdNm": "벽돌구조",
        "mainPurpsCdNm": "단독주택",
        "hhldCnt": 0,
        "fmlyCnt": 1,
        "allHoCnt": 1,
        "generationUnit": "가구",
        "grndFlrCnt": 1,
        "ugrndFlrCnt": 0,
        "rideUseElvtCnt": 0,
        "emgenUseElvtCnt": 0,
        "totalElvtCnt": 0,
        "elvtInfo": "",
        "atchBldCnt": 0,
        "totDongTotArea": 0,
        "indrMechUtcnt": 0,
        "oudrMechUtcnt": 0,
        "indrAutoUtcnt": 0,
        "oudrAutoUtcnt": 0,
        "etcParkInfo": "",
        "totalParkingCnt": 0,
        "useAprDay": "1986.12",
        "engrRat": 0,
        "engrEpi": 0,
        "gnBldCert": 0,
        "itgBldCert": 0,
        "bldX": 0,
        "bldY": 0,
        "jiyukNmLink": "",
        "jiyukCount": 0,
        "jiguNmLink": "",
        "jiguCount": 0,
        "guyukNmLink": "",
        "guyukCount": 0,
        "naid": "4182044482600100002200000",
        "pnu": "4182032521107190000",
        "bsource": "030100",
        "serviceYn": "Y",
        "hoCnt": 0,
        "exposureBldName": False,
    },
    "articlePhotos": [],
    "marketPrice": {},
    "articleTax": {
        "acquisitionTax": 1650000,
        "registTax": 0,
        "registFee": 38,
        "brokerFee": 800000,
        "maxBrokerFee": 0.5,
        "eduTax": 165000,
        "specialTax": 0,
        "registApplyFee": 0,
        "digitalRevenuStamp": 0,
        "nationHouseBond": 0,
        "totalPrice": 1815000,
    },
    "landPrice": {
        "hscpNo": "",
        "hscpType": "",
        "hscpNm": "",
        "bildNo": "",
        "dongNm": "",
        "hoNm": "",
        "hoFloor": "0",
        "lineNo": "",
        "pilotiYn": "",
        "existHo": "",
        "price": "0",
        "prevPrice": "0",
        "ptpNo": "",
        "supplyArea": "0",
        "totalArea": "0",
        "stdYear": 0,
        "stdYmd": 0,
    },
    "tabCategory": "",
    "schools": [],
    "realtor": {
        "realtorId": "dbsgmlwjd082508",
        "realtorName": "청평만복부동산공인중개사사무소",
        "representativeName": "윤희정",
        "address": "경기도 가평군 청평면 청평중앙로 13 1층 (청평리)",
        "establishRegistrationNo": "41650202100011",
        "profileImageUrl": "/20230118_40/rltr_profile_1674019404273WL7vj_JPEG/dbsgmlwjd082508_cropImage.jpg",
        "profileFullImageUrl": "/20221229_287/rltr_profile_1672274275052hOD4E_JPEG/1672274274625_%C1%A6%B8%F1_%BE%F8%C0%BD.jpg",
        "representativeTelNo": "031-585-4980",
        "cellPhoneNo": "010-6672-4484",
        "isCellPhoneExposure": True,
        "isRepresentativeTelExposure": True,
        "exposeTelTypeCode": "ALL",
    },
    "location": {"cityName": "경기도", "divisionName": "가평군", "sectionName": "청평면", "detailAddress": "경기도 가평군 청평면 청평리"},
    "isValidArticle": True,
    "maintenanceCost": {},
    "articleTitle": "단독",
    "articleSubTitle": "",
    "articleHeaderSubTitle": "단독",
    "dealerTelInfo": {
        "dealerNm": "청평만복부동산공인중개사사무소",
        "addr": "경기도 가평군 청평면 청평중앙로 13 1층 (청평리)",
        "expsTelTpCd": "ALL",
        "tradTpNm": "매매",
        "atclNm": "단독 단독",
        "atclStatCd": "R0",
        "bildNm": "단독",
        "atclNo": "2321886130",
        "prcInfo": "16500",
        "leasePrc": "1억 6,500",
        "repTelNo": "031-585-4980",
        "realtorRepImgPath": "/20230118_40/rltr_profile_1674019404273WL7vj_JPEG/dbsgmlwjd082508_cropImage.jpg",
        "cellPhoneNo": "010-6672-4484",
        "phoneNoForSMS": "010-6672-4484",
    },
}
