{
    "article": {
        "articleNo": "2318967952",
        "articleName": "가평센트럴파크더스카이 102동",
        "articleSubName": "",
        "cpId": "bizmk",
        "cortarNo": "4182025000",
        "hscpNo": "140799",
        "ptpNo": "1",
        "ptpName": "132OT",
        "tradeBuildingTypeCode": "OFCT",
        "exposeStartYMD": "20230504",
        "exposeEndYMD": "20230603",
        "buildNo": "1",
        "articleConfirmYMD": "20230504",
        "tradeCompleteYN": "N",
        "aptName": "가평센트럴파크더스카이",
        "aptHeatMethodTypeName": "개별난방",
        "aptHeatFuelTypeName": "도시가스",
        "aptParkingCount": "38",
        "aptParkingCountPerHousehold": "1.02",
        "aptHouseholdCount": "37",
        "aptConstructionCompanyName": "(주)일군토건",
        "aptUseApproveYmd": "202208",
        "isaleDealRestrictionCode": "N",
        "totalDongCount": 1,
        "articleStatusCode": "R0",
        "articleTypeCode": "A02",
        "realestateTypeCode": "OPST",
        "realestateTypeName": "오피스텔",
        "tradeTypeCode": "A1",
        "tradeTypeName": "매매",
        "verificationTypeCode": "DOCV2",
        "applyYN": "N",
        "directTradeYN": "N",
        "mapLocationIndicationYn": "Y",
        "latitude": "37.831684",
        "longitude": "127.512035",
        "cityNo": "4100000000",
        "cityName": "경기도",
        "divisionName": "가평군",
        "sectionName": "가평읍",
        "householdCountByPtp": "37",
        "realtorId": "jalee1970",
        "walkingTimeToNearSubway": 0,
        "complexGrandPlanList": [
            {
                "imageId": "140799@1@20210901202330959260",
                "imageTypeCode": "BASE",
                "dimensionTypeCode": "2D",
                "floorTypeCode": "SFLR",
                "viewCode": "DFT",
                "imageNumberCode": "0",
                "imageUrl": "/20210901_271/land_naver_1630495411054W0fkp_JPEG/140799120210901202330959260090120233123000000.jpg",
                "pyeongNo": "1",
                "pyeongName": "132OT",
                "imageOrder": "0",
            }
        ],
        "roomNumber": "604",
        "detailAddress": "",
        "exposureAddress": "경기도 가평군 가평읍",
        "roomCount": "2",
        "bathroomCount": "2",
        "moveInTypeCode": "MV001",
        "moveInTypeName": "즉시입주",
        "moveInDiscussionPossibleYN": "협의가능",
        "moveInPossibleYmd": "20240930",
        "monthlyManagementCost": 0,
        "originBuildingName": "102",
        "buildingName": "102동",
        "articleFeatureDescription": "3000만원 다운,세안고,등기완료",
        "detailDescription": "현재 세입자 있어 월세 나오는 매물임\r\n방2.넓은 거실.풀옵션 장착\r\n가평 중심지의 핫한 위치\r\n은행.병원.초.중고,관공서 초근접의 편리한 생활권.\r\n터미널도보로 가평역 환승.서울 출퇴근 용이함.\r\n기타 궁금한 사항은 전화주세요.031-581-3322\r\n가평군청 옆 새미래부동산입니다~~\r\n\r\n\r\n",
        "parkingCount": 38,
        "parkingPerHouseholdCount": "1.02",
        "parkingPossibleYN": "N",
        "duplexYN": "N",
        "floorLayerName": "단층",
        "hasBuildingUnitInfo": False,
        "lawUsage": "제2종 근린생활시설",
        "tagList": ["2년이내", "화장실두개", "대형평수", "방두개"],
        "isInterest": False,
        "isFalseHoodDeclared": False,
        "kisoConnectionYN": "Y",
        "detailAddressYn": "N",
        "isComplex": True,
        "isOwnerTradeCompleted": False,
    },
    "addition": {
        "articleNo": "2318967952",
        "articleName": "가평센트럴파크더스카이",
        "articleStatus": "R0",
        "realEstateTypeCode": "OPST",
        "realEstateTypeName": "오피스텔",
        "articleRealEstateTypeCode": "A02",
        "articleRealEstateTypeName": "오피스텔",
        "tradeTypeCode": "A1",
        "tradeTypeName": "매매",
        "verificationTypeCode": "DOCV2",
        "floorInfo": "6/22",
        "priceChangeState": "SAME",
        "isPriceModification": False,
        "dealOrWarrantPrc": "2억 2,400",
        "areaName": "132OT",
        "area1": 132,
        "area2": 59,
        "direction": "남서향",
        "articleConfirmYmd": "20230504",
        "representativeImgUrl": "/20230504_99/land_naver_16831693522745FiV1_JPEG/20220722_163142.jpg",
        "representativeImgTypeCode": "10",
        "representativeImgThumb": "f130_98",
        "siteImageCount": 0,
        "articleFeatureDesc": "3000만원 다운,세안고,등기완료",
        "tagList": ["2년이내", "화장실두개", "대형평수", "방두개"],
        "buildingName": "102동",
        "sameAddrCnt": 1,
        "sameAddrDirectCnt": 0,
        "sameAddrMaxPrc": "2억 2,400",
        "sameAddrMinPrc": "2억 2,400",
        "cpid": "bizmk",
        "cpName": "매경부동산",
        "cpPcArticleLinkUseAtArticleTitleYn": False,
        "cpPcArticleLinkUseAtCpNameYn": False,
        "cpMobileArticleLinkUseAtArticleTitleYn": False,
        "cpMobileArticleLinkUseAtCpNameYn": False,
        "latitude": "37.831684",
        "longitude": "127.512035",
        "isLocationShow": False,
        "realtorName": "새미래부동산중개사무소",
        "realtorId": "jalee1970",
        "tradeCheckedByOwner": False,
        "isDirectTrade": False,
        "isInterest": False,
        "isComplex": True,
    },
    "noneHscp": {},
    "space": {
        "supplySpace": 132.39,
        "exclusiveSpace": 59.54,
        "groundSpace": 0,
        "totalSpace": 0,
        "buildingSpace": 0,
        "expectSpace": 0,
        "groundShareSpace": 0,
        "exclusiveRate": "45",
    },
    "facility": {
        "directionTypeCode": "WS",
        "directionTypeName": "남서향",
        "directionBaseTypeCode": "LVRM",
        "directionBaseTypeName": "거실 기준",
        "entranceTypeCode": "10",
        "entranceTypeName": "계단식",
        "usageTypeCode": "30",
        "usageTypeName": "겸용",
        "airconFacilityList": "AC003",
        "airconFacilities": ["천장에어컨"],
        "lifeFacilityList": "LF001,LF002,LF007,LF009,LF010,LF016,LF015,LF014",
        "lifeFacilities": ["붙박이장", "식탁", "신발장", "냉장고", "세탁기", "샤워부스", "싱크대", "가스레인지"],
        "securityFacilityList": "SEC02,SEC03,SEC04,SEC07",
        "securityFacilities": ["비디오폰", "인터폰", "카드키", "현관보안"],
        "etcFacilityList": "ETC01,ETC02",
        "etcFacilities": ["엘리베이터", "화재경보기"],
        "floorAreaRatio": "-",
        "buildingCoverageRatio": "-",
    },
    "floor": {
        "totalFloorCount": "22",
        "undergroundFloorCount": "-",
        "uppergroundFloorCount": "-",
        "floorTypeCode": "00",
        "floorInputMethodCode": "10",
        "correspondingFloorCount": "6",
        "buildingHighestFloor": "22",
        "complexHighestFloor": "22",
    },
    "price": {
        "rentPrice": 0,
        "dealPrice": 22400,
        "warrantPrice": 0,
        "allWarrantPrice": 1000,
        "financeTypeCode": "20",
        "financePrice": 14000,
        "premiumPrice": 0,
        "isalePrice": 0,
        "allRentPrice": 85,
        "priceBySpace": 559,
        "bondPrice": 0,
        "middlePayment": 0,
    },
    "ground": {},
    "rebuild": {},
    "oneroom": {},
    "redevelop": {},
    "buildingRegister": {},
    "articlePhotos": [
        {
            "imageKey": "2318967952",
            "imageSrc": "/20230504_59/land_naver_1683169352274BpTGu_JPEG/504%C8%A3.jpg",
            "imageType": "10",
            "imageId": "2318967952@20230504115313035707",
            "realtorName": "새미래부동산중개사무소",
            "smallCategoryName": "",
            "registYmdt": "20230504115314",
            "imageOrder": 5,
        },
        {
            "imageKey": "2318967952",
            "imageSrc": "/20230504_38/land_naver_1683169352273f85ut_JPEG/504.jpg",
            "imageType": "10",
            "imageId": "2318967952@20230504115314014395",
            "realtorName": "새미래부동산중개사무소",
            "smallCategoryName": "",
            "registYmdt": "20230504115314",
            "imageOrder": 5,
        },
        {
            "imageKey": "2318967952",
            "imageSrc": "/20230504_119/land_naver_1683169352305gx7hE_JPEG/20220722_163448.jpg",
            "imageType": "10",
            "imageId": "2318967952@20230504115314021568",
            "realtorName": "새미래부동산중개사무소",
            "smallCategoryName": "",
            "registYmdt": "20230504115314",
            "imageOrder": 5,
        },
        {
            "imageKey": "2318967952",
            "imageSrc": "/20230504_99/land_naver_16831693522745FiV1_JPEG/20220722_163142.jpg",
            "imageType": "10",
            "imageId": "2318967952@20230504115314027983",
            "realtorName": "새미래부동산중개사무소",
            "smallCategoryName": "",
            "registYmdt": "20230504115314",
            "imageOrder": 5,
        },
        {
            "imageKey": "2318967952",
            "imageSrc": "/20230504_13/land_naver_1683169352305r7t5j_JPEG/20220722_163527.jpg",
            "imageType": "10",
            "imageId": "2318967952@20230504115314034292",
            "realtorName": "새미래부동산중개사무소",
            "smallCategoryName": "",
            "registYmdt": "20230504115314",
            "imageOrder": 5,
        },
        {
            "imageKey": "2318967952",
            "imageSrc": "/20230504_186/land_naver_1683169352309U9TBi_JPEG/20220722_163153.jpg",
            "imageType": "10",
            "imageId": "2318967952@20230504115314040791",
            "realtorName": "새미래부동산중개사무소",
            "smallCategoryName": "",
            "registYmdt": "20230504115314",
            "imageOrder": 5,
        },
    ],
    "marketPrice": {},
    "articleTax": {
        "acquisitionTax": 8960000,
        "registTax": 0,
        "registFee": 42,
        "brokerFee": 1120000,
        "maxBrokerFee": 0.5,
        "eduTax": 896000,
        "specialTax": 448000,
        "registApplyFee": 0,
        "digitalRevenuStamp": 0,
        "nationHouseBond": 0,
        "totalPrice": 10304000,
    },
    "landPrice": {
        "hscpNo": "",
        "hscpType": "",
        "hscpNm": "",
        "bildNo": "",
        "dongNm": "",
        "hoNm": "",
        "hoFloor": "0",
        "lineNo": "",
        "pilotiYn": "",
        "existHo": "",
        "price": "0",
        "prevPrice": "0",
        "ptpNo": "",
        "supplyArea": "0",
        "totalArea": "0",
        "stdYear": 0,
        "stdYmd": 0,
    },
    "tabCategory": "",
    "schools": [
        {
            "walkTime": 0,
            "schoolCode": "J100000882",
            "schoolName": "가평초등학교",
            "organizationType": "공립",
            "studentCountPerTeacher": 16.8,
            "studentCountPerClassroom": 25,
            "maleStudentCount": 0,
            "femaleStudentCount": 0,
            "maleTeacherCount": 0,
            "femaleTeacherCount": 0,
            "firstYearClassroomCount": 0,
            "secondYearClassroomCount": 0,
            "thirdYearClassroomCount": 0,
            "fourthYearClassroomCount": 0,
            "fifthYearClassroomCount": 0,
            "sixthYearClassroomCount": 0,
            "firstYearStudentCount": 0,
            "secondYearStudentCount": 0,
            "thirdYearStudentCount": 0,
            "fourthYearStudentCount": 0,
            "fifthYearStudentCount": 0,
            "sixthYearStudentCount": 0,
            "specialClassroomCount": 0,
            "specialClassroomStudentCount": 0,
            "totalClassroomCount": 0,
            "totalStudentCount": 0,
            "maleEmployeeCount": 0,
            "femaleEmployeeCount": 0,
            "innerCounselorCount": 0,
            "outerCounselorCount": 0,
            "afterSchoolProgramCount": 0,
            "afterSchoolStudentCount": 0,
            "libraryBookCount": 0,
            "libraryBookCountPerPerson": 0,
            "mealServicePricePerStudent": 0,
            "mealServiceSupportStudentCount": 0,
            "mealServiceYearlySupportAmount": 0,
            "averageStudentCountPerClassroomOnCity": 0,
            "averageStudentCountPerTeacherOnCity": 0,
            "averageStudentCountPerClassroomOnDivision": 0,
            "averageStudentCountPerTeacherOnDivision": 0,
        }
    ],
    "realtor": {
        "realtorId": "jalee1970",
        "realtorName": "새미래부동산중개사무소",
        "representativeName": "이정아",
        "address": "경기 가평군 가평읍 읍내리515-1",
        "establishRegistrationNo": "가-121-268",
        "representativeTelNo": "031-581-3322",
        "cellPhoneNo": "010-2224-8328",
        "isCellPhoneExposure": True,
        "isRepresentativeTelExposure": True,
        "exposeTelTypeCode": "TEL",
    },
    "location": {
        "cityName": "경기도",
        "divisionName": "가평군",
        "sectionName": "가평읍",
        "detailAddress": "경기도 가평군 가평읍 읍내리 457-5",
        "complexLocation": {"detailAddress": "읍내리 457-5"},
    },
    "isValidArticle": True,
    "maintenanceCost": {},
    "articleTitle": "가평센트럴파크더스카이 102동",
    "articleSubTitle": "",
    "articleHeaderSubTitle": "가평센트럴파크더스카이 102동",
    "dealerTelInfo": {
        "dealerNm": "새미래부동산중개사무소",
        "addr": "경기 가평군 가평읍 읍내리515-1",
        "expsTelTpCd": "TEL",
        "tradTpNm": "매매",
        "atclNm": "가평센트럴파크더스카이 102동",
        "atclStatCd": "R0",
        "bildNm": "102동",
        "atclNo": "2318967952",
        "prcInfo": "22400",
        "leasePrc": "2억 2,400",
        "repTelNo": "031-581-3322",
        "cellPhoneNo": "",
    },
}
