{
    "code": "success",
    "hasPaidPreSale": false,
    "more": true,
    "TIME": false,
    "z": 14,
    "page": 1,
    "body": [
        {
            "atclNo": "2320302358",
            "cortarNo": "4131010300",
            "atclNm": "빌라",
            "atclStatCd": "R0",
            "rletTpCd": "C02",
            "uprRletTpCd": "C03",
            "rletTpNm": "빌라",
            "tradTpCd": "A1",
            "tradTpNm": "매매",
            "vrfcTpCd": "OWNER",
            "flrInfo": "5/5",
            "prc": 29000,
            "rentPrc": 0,
            "hanPrc": "2억 9,000",
            "spc1": "84",
            "spc2": "62.16",
            "direction": "남향",
            "atclCfmYmd": "23.05.12.",
            "lat": 37.607341,
            "lng": 127.138542,
            "atclFetrDesc": "구리역접근성좋음 주위에식당학교공원등 위치좋음",
            "tagList": ["25년이상", "탑층", "방세개", "화장실한개"],
            "bildNm": "",
            "minute": 0,
            "sameAddrCnt": 1,
            "sameAddrDirectCnt": 0,
            "cpid": "R114",
            "cpNm": "부동산114",
            "cpCnt": 1,
            "rltrNm": "NEW미래부동산공인중개사사무소",
            "directTradYn": "N",
            "minMviFee": 0,
            "maxMviFee": 0,
            "etRoomCnt": 0,
            "tradePriceHan": "",
            "tradeRentPrice": 0,
            "tradeCheckedByOwner": false,
            "cpLinkVO": {
                "cpId": "R114",
                "mobileArticleUrl": "https://m.r114.com/?_c=redirect&_m=ArticleFromNbp&UID=",
                "mobileArticleLinkTypeCode": "ALL",
                "mobileBmsInspectPassYn": "Y",
                "pcArticleLinkUseAtArticleTitle": false,
                "pcArticleLinkUseAtCpName": false,
                "mobileArticleLinkUseAtArticleTitle": true,
                "mobileArticleLinkUseAtCpName": true,
            },
            "dtlAddrYn": "N",
            "dtlAddr": "",
        },
        {
            "atclNo": "2320300679",
            "cortarNo": "4131010300",
            "atclNm": "빌라",
            "atclStatCd": "R0",
            "rletTpCd": "C02",
            "uprRletTpCd": "C03",
            "rletTpNm": "빌라",
            "tradTpCd": "A1",
            "tradTpNm": "매매",
            "vrfcTpCd": "OWNER",
            "flrInfo": "6/6",
            "prc": 40000,
            "rentPrc": 0,
            "hanPrc": "4억",
            "spc1": "60",
            "spc2": "53.55",
            "direction": "남동향",
            "atclCfmYmd": "23.05.12.",
            "lat": 37.604062,
            "lng": 127.135118,
            "atclFetrDesc": "전세안고매매 투자로좋아요",
            "tagList": ["25년이상", "소형평수", "탑층", "방세개"],
            "bildNm": "",
            "minute": 0,
            "sameAddrCnt": 1,
            "sameAddrDirectCnt": 0,
            "cpid": "R114",
            "cpNm": "부동산114",
            "cpCnt": 1,
            "rltrNm": "NEW미래부동산공인중개사사무소",
            "directTradYn": "N",
            "minMviFee": 0,
            "maxMviFee": 0,
            "etRoomCnt": 0,
            "tradePriceHan": "",
            "tradeRentPrice": 0,
            "tradeCheckedByOwner": false,
            "cpLinkVO": {
                "cpId": "R114",
                "mobileArticleUrl": "https://m.r114.com/?_c=redirect&_m=ArticleFromNbp&UID=",
                "mobileArticleLinkTypeCode": "ALL",
                "mobileBmsInspectPassYn": "Y",
                "pcArticleLinkUseAtArticleTitle": false,
                "pcArticleLinkUseAtCpName": false,
                "mobileArticleLinkUseAtArticleTitle": true,
                "mobileArticleLinkUseAtCpName": true,
            },
            "dtlAddrYn": "N",
            "dtlAddr": "",
        },
        {
            "atclNo": "2320227502",
            "cortarNo": "4131010300",
            "atclNm": "빌라",
            "atclStatCd": "R0",
            "rletTpCd": "C02",
            "uprRletTpCd": "C03",
            "rletTpNm": "빌라",
            "tradTpCd": "A1",
            "tradTpNm": "매매",
            "vrfcTpCd": "OWNER",
            "flrInfo": "3/4",
            "prc": 30000,
            "rentPrc": 0,
            "hanPrc": "3억",
            "spc1": "65",
            "spc2": "45.21",
            "direction": "남서향",
            "atclCfmYmd": "23.05.12.",
            "lat": 37.604917,
            "lng": 127.13897,
            "tagList": ["25년이내", "방두개", "화장실한개", "고층"],
            "bildNm": "",
            "minute": 0,
            "sameAddrCnt": 1,
            "sameAddrDirectCnt": 0,
            "cpid": "bizmk",
            "cpNm": "매경부동산",
            "cpCnt": 1,
            "rltrNm": "어반포레에이스 공인중개사사무소",
            "directTradYn": "N",
            "minMviFee": 0,
            "maxMviFee": 0,
            "etRoomCnt": 0,
            "tradePriceHan": "",
            "tradeRentPrice": 0,
            "tradeCheckedByOwner": false,
            "cpLinkVO": {
                "cpId": "bizmk",
                "mobileArticleLinkTypeCode": "NONE",
                "mobileBmsInspectPassYn": "Y",
                "pcArticleLinkUseAtArticleTitle": false,
                "pcArticleLinkUseAtCpName": false,
                "mobileArticleLinkUseAtArticleTitle": false,
                "mobileArticleLinkUseAtCpName": false,
            },
            "dtlAddrYn": "N",
            "dtlAddr": "",
        },
        {
            "atclNo": "2319649539",
            "cortarNo": "4131010300",
            "atclNm": "빌라",
            "atclStatCd": "R0",
            "rletTpCd": "C02",
            "uprRletTpCd": "C03",
            "rletTpNm": "빌라",
            "tradTpCd": "A1",
            "tradTpNm": "매매",
            "vrfcTpCd": "OWNER",
            "flrInfo": "3/4",
            "prc": 41000,
            "rentPrc": 0,
            "hanPrc": "4억 1,000",
            "spc1": "62",
            "spc2": "51.6",
            "direction": "남서향",
            "atclCfmYmd": "23.05.09.",
            "lat": 37.601955,
            "lng": 127.139282,
            "atclFetrDesc": "공정한. 초역세권. 투자추천. 방3개. 화장실1개",
            "tagList": ["25년이상", "소형평수", "방세개", "화장실한개"],
            "bildNm": "",
            "minute": 0,
            "sameAddrCnt": 1,
            "sameAddrDirectCnt": 0,
            "cpid": "SERVE",
            "cpNm": "부동산써브",
            "cpCnt": 1,
            "rltrNm": "공정한사람들공인중개사사무소",
            "directTradYn": "N",
            "minMviFee": 0,
            "maxMviFee": 0,
            "etRoomCnt": 0,
            "tradePriceHan": "",
            "tradeRentPrice": 0,
            "tradeCheckedByOwner": false,
            "cpLinkVO": {
                "cpId": "SERVE",
                "mobileArticleUrl": "http://m.serve.co.kr/naver/rd.asp?UID=",
                "mobileArticleLinkTypeCode": "CPNAMEONLY",
                "mobileBmsInspectPassYn": "Y",
                "pcArticleLinkUseAtArticleTitle": false,
                "pcArticleLinkUseAtCpName": false,
                "mobileArticleLinkUseAtArticleTitle": false,
                "mobileArticleLinkUseAtCpName": true,
            },
            "dtlAddrYn": "N",
            "dtlAddr": "",
        },
        {
            "atclNo": "2319649784",
            "cortarNo": "4131010300",
            "atclNm": "연립",
            "atclStatCd": "R0",
            "rletTpCd": "C02",
            "uprRletTpCd": "C03",
            "rletTpNm": "빌라",
            "tradTpCd": "A1",
            "tradTpNm": "매매",
            "vrfcTpCd": "OWNER",
            "flrInfo": "1/4",
            "prc": 50000,
            "rentPrc": 0,
            "hanPrc": "5억",
            "spc1": "85",
            "spc2": "53.19",
            "direction": "남서향",
            "atclCfmYmd": "23.05.09.",
            "lat": 37.602007,
            "lng": 127.139572,
            "atclFetrDesc": "공정한. 초역세권. 투자추천. 방3개",
            "tagList": ["25년이상", "1층", "방세개", "화장실한개"],
            "bildNm": "",
            "minute": 0,
            "sameAddrCnt": 1,
            "sameAddrDirectCnt": 0,
            "cpid": "SERVE",
            "cpNm": "부동산써브",
            "cpCnt": 1,
            "rltrNm": "공정한사람들공인중개사사무소",
            "directTradYn": "N",
            "minMviFee": 0,
            "maxMviFee": 0,
            "etRoomCnt": 0,
            "tradePriceHan": "",
            "tradeRentPrice": 0,
            "tradeCheckedByOwner": false,
            "cpLinkVO": {
                "cpId": "SERVE",
                "mobileArticleUrl": "http://m.serve.co.kr/naver/rd.asp?UID=",
                "mobileArticleLinkTypeCode": "CPNAMEONLY",
                "mobileBmsInspectPassYn": "Y",
                "pcArticleLinkUseAtArticleTitle": false,
                "pcArticleLinkUseAtCpName": false,
                "mobileArticleLinkUseAtArticleTitle": false,
                "mobileArticleLinkUseAtCpName": true,
            },
            "dtlAddrYn": "N",
            "dtlAddr": "",
        },
        {
            "atclNo": "2321155458",
            "cortarNo": "4131010300",
            "atclNm": "빌라",
            "atclStatCd": "R0",
            "rletTpCd": "C02",
            "uprRletTpCd": "C03",
            "rletTpNm": "빌라",
            "tradTpCd": "A1",
            "tradTpNm": "매매",
            "vrfcTpCd": "DOC",
            "flrInfo": "2/3",
            "prc": 38000,
            "rentPrc": 0,
            "hanPrc": "3억 8,000",
            "spc1": "54",
            "spc2": "48.72",
            "direction": "남향",
            "atclCfmYmd": "23.05.18.",
            "lat": 37.605044,
            "lng": 127.136156,
            "atclFetrDesc": "샷시포함올수리확장 투자환영 인창B구역 가격조절가능함 인창공원근방",
            "tagList": ["25년이상", "올수리", "소형평수", "방세개"],
            "bildNm": "",
            "minute": 0,
            "sameAddrCnt": 1,
            "sameAddrDirectCnt": 0,
            "cpid": "SERVE",
            "cpNm": "부동산써브",
            "cpCnt": 1,
            "rltrNm": "동양드림부동산공인중개사",
            "directTradYn": "N",
            "minMviFee": 0,
            "maxMviFee": 0,
            "etRoomCnt": 0,
            "tradePriceHan": "",
            "tradeRentPrice": 0,
            "tradeCheckedByOwner": false,
            "cpLinkVO": {
                "cpId": "SERVE",
                "mobileArticleUrl": "http://m.serve.co.kr/naver/rd.asp?UID=",
                "mobileArticleLinkTypeCode": "CPNAMEONLY",
                "mobileBmsInspectPassYn": "Y",
                "pcArticleLinkUseAtArticleTitle": false,
                "pcArticleLinkUseAtCpName": false,
                "mobileArticleLinkUseAtArticleTitle": false,
                "mobileArticleLinkUseAtCpName": true,
            },
            "dtlAddrYn": "N",
            "dtlAddr": "",
        },
        {
            "atclNo": "2319342032",
            "cortarNo": "4131010300",
            "atclNm": "빌라",
            "atclStatCd": "R0",
            "rletTpCd": "C02",
            "uprRletTpCd": "C03",
            "rletTpNm": "빌라",
            "tradTpCd": "A1",
            "tradTpNm": "매매",
            "vrfcTpCd": "OWNER",
            "flrInfo": "3/3",
            "prc": 39000,
            "rentPrc": 0,
            "hanPrc": "3억 9,000",
            "spc1": "47",
            "spc2": "41.76",
            "direction": "남향",
            "atclCfmYmd": "23.05.06.",
            "lat": 37.601781,
            "lng": 127.139289,
            "atclFetrDesc": "재개발 추진 중인 구리시 초역세권 빌라 전세안고 매매",
            "tagList": ["25년이상", "소형평수", "탑층", "방두개"],
            "bildNm": "",
            "minute": 0,
            "sameAddrCnt": 1,
            "sameAddrDirectCnt": 0,
            "cpid": "bizmk",
            "cpNm": "매경부동산",
            "cpCnt": 1,
            "rltrNm": "쌍용공인중개사사무소",
            "directTradYn": "N",
            "minMviFee": 0,
            "maxMviFee": 0,
            "etRoomCnt": 0,
            "tradePriceHan": "",
            "tradeRentPrice": 0,
            "tradeCheckedByOwner": false,
            "cpLinkVO": {
                "cpId": "bizmk",
                "mobileArticleLinkTypeCode": "NONE",
                "mobileBmsInspectPassYn": "Y",
                "pcArticleLinkUseAtArticleTitle": false,
                "pcArticleLinkUseAtCpName": false,
                "mobileArticleLinkUseAtArticleTitle": false,
                "mobileArticleLinkUseAtCpName": false,
            },
            "dtlAddrYn": "N",
            "dtlAddr": "",
        },
        {
            "atclNo": "2320664967",
            "cortarNo": "4131010300",
            "atclNm": "빌라",
            "atclStatCd": "R0",
            "rletTpCd": "C02",
            "uprRletTpCd": "C03",
            "rletTpNm": "빌라",
            "tradTpCd": "A1",
            "tradTpNm": "매매",
            "vrfcTpCd": "DOC",
            "flrInfo": "B1/4",
            "prc": 35000,
            "rentPrc": 0,
            "hanPrc": "3억 5,000",
            "spc1": "54",
            "spc2": "49.74",
            "direction": "남향",
            "atclCfmYmd": "23.05.15.",
            "repImgUrl": "/20230515_197/land_naver_1684129109984WK8eO_JPEG/1664958893362649.jpg",
            "repImgTpCd": "10",
            "repImgThumb": "f130_98",
            "lat": 37.602831,
            "lng": 127.136546,
            "atclFetrDesc": "인창비구역 재개발 투자매물, 아파트입주권 투자",
            "tagList": ["25년이상", "화장실한개", "소형평수"],
            "bildNm": "",
            "minute": 0,
            "sameAddrCnt": 1,
            "sameAddrDirectCnt": 0,
            "cpid": "NEONET",
            "cpNm": "부동산뱅크",
            "cpCnt": 1,
            "rltrNm": "스피드부동산중개법인",
            "directTradYn": "N",
            "minMviFee": 0,
            "maxMviFee": 0,
            "etRoomCnt": 0,
            "tradePriceHan": "",
            "tradeRentPrice": 0,
            "tradeCheckedByOwner": false,
            "cpLinkVO": {
                "cpId": "NEONET",
                "mobileArticleLinkTypeCode": "NONE",
                "mobileBmsInspectPassYn": "Y",
                "pcArticleLinkUseAtArticleTitle": false,
                "pcArticleLinkUseAtCpName": false,
                "mobileArticleLinkUseAtArticleTitle": false,
                "mobileArticleLinkUseAtCpName": false,
            },
            "dtlAddrYn": "N",
            "dtlAddr": "",
        },
        {
            "atclNo": "2320648073",
            "cortarNo": "4131010300",
            "atclNm": "빌라",
            "atclStatCd": "R0",
            "rletTpCd": "C02",
            "uprRletTpCd": "C03",
            "rletTpNm": "빌라",
            "tradTpCd": "A1",
            "tradTpNm": "매매",
            "vrfcTpCd": "DOC",
            "flrInfo": "2/4",
            "prc": 27000,
            "rentPrc": 0,
            "hanPrc": "2억 7,000",
            "spc1": "55",
            "spc2": "51.84",
            "direction": "북서향",
            "atclCfmYmd": "23.05.15.",
            "repImgUrl": "/20230515_77/land_naver_1684127966987i57dc_JPEG/14146161_202351512243710.jpg",
            "repImgTpCd": "10",
            "repImgThumb": "f130_98",
            "lat": 37.607729,
            "lng": 127.137463,
            "atclFetrDesc": "공실, 깔끔함, 미닫이 거실사용가능, 주변공원, 8호선 개통",
            "tagList": ["25년이상", "소형평수", "방세개"],
            "bildNm": "",
            "minute": 0,
            "sameAddrCnt": 1,
            "sameAddrDirectCnt": 0,
            "cpid": "SERVE",
            "cpNm": "부동산써브",
            "cpCnt": 1,
            "rltrNm": "황금사과 공인중개사사무소",
            "directTradYn": "N",
            "minMviFee": 0,
            "maxMviFee": 0,
            "etRoomCnt": 0,
            "tradePriceHan": "",
            "tradeRentPrice": 0,
            "tradeCheckedByOwner": false,
            "cpLinkVO": {
                "cpId": "SERVE",
                "mobileArticleUrl": "http://m.serve.co.kr/naver/rd.asp?UID=",
                "mobileArticleLinkTypeCode": "CPNAMEONLY",
                "mobileBmsInspectPassYn": "Y",
                "pcArticleLinkUseAtArticleTitle": false,
                "pcArticleLinkUseAtCpName": false,
                "mobileArticleLinkUseAtArticleTitle": false,
                "mobileArticleLinkUseAtCpName": true,
            },
            "dtlAddrYn": "N",
            "dtlAddr": "",
        },
        {
            "atclNo": "2319041459",
            "cortarNo": "4131010300",
            "atclNm": "빌라",
            "atclStatCd": "R0",
            "rletTpCd": "C02",
            "uprRletTpCd": "C03",
            "rletTpNm": "빌라",
            "tradTpCd": "A1",
            "tradTpNm": "매매",
            "vrfcTpCd": "OWNER",
            "flrInfo": "2/4",
            "prc": 31000,
            "rentPrc": 0,
            "hanPrc": "3억 1,000",
            "spc1": "44",
            "spc2": "44.19",
            "direction": "서향",
            "atclCfmYmd": "23.05.04.",
            "lat": 37.604917,
            "lng": 127.13897,
            "atclFetrDesc": "2년전샷시포함올수리 세안고 공원뷰",
            "tagList": ["25년이내", "올수리", "소형평수", "방세개"],
            "bildNm": "",
            "minute": 0,
            "sameAddrCnt": 1,
            "sameAddrDirectCnt": 0,
            "cpid": "SERVE",
            "cpNm": "부동산써브",
            "cpCnt": 1,
            "rltrNm": "베스트가대라곡공인중개사사무소",
            "directTradYn": "N",
            "minMviFee": 0,
            "maxMviFee": 0,
            "etRoomCnt": 0,
            "tradePriceHan": "",
            "tradeRentPrice": 0,
            "tradeCheckedByOwner": false,
            "cpLinkVO": {
                "cpId": "SERVE",
                "mobileArticleUrl": "http://m.serve.co.kr/naver/rd.asp?UID=",
                "mobileArticleLinkTypeCode": "CPNAMEONLY",
                "mobileBmsInspectPassYn": "Y",
                "pcArticleLinkUseAtArticleTitle": false,
                "pcArticleLinkUseAtCpName": false,
                "mobileArticleLinkUseAtArticleTitle": false,
                "mobileArticleLinkUseAtCpName": true,
            },
            "dtlAddrYn": "N",
            "dtlAddr": "",
        },
        {
            "atclNo": "2320222776",
            "cortarNo": "4131010300",
            "atclNm": "빌라",
            "atclStatCd": "R0",
            "rletTpCd": "C02",
            "uprRletTpCd": "C03",
            "rletTpNm": "빌라",
            "tradTpCd": "A1",
            "tradTpNm": "매매",
            "vrfcTpCd": "DOC",
            "flrInfo": "1/3",
            "prc": 40000,
            "rentPrc": 0,
            "hanPrc": "4억",
            "spc1": "50",
            "spc2": "45.5",
            "direction": "남향",
            "atclCfmYmd": "23.05.12.",
            "lat": 37.604262,
            "lng": 127.136415,
            "atclFetrDesc": "전세끼고매매,지하철8호선 개통예정, 경의중앙선 더블역세권, 투자가치 좋음",
            "tagList": ["25년이상", "1층", "소형평수", "방두개"],
            "bildNm": "",
            "minute": 0,
            "sameAddrCnt": 1,
            "sameAddrDirectCnt": 0,
            "cpid": "SERVE",
            "cpNm": "부동산써브",
            "cpCnt": 1,
            "rltrNm": "예감좋은부동산공인중개사사무소",
            "directTradYn": "N",
            "minMviFee": 0,
            "maxMviFee": 0,
            "etRoomCnt": 0,
            "tradePriceHan": "",
            "tradeRentPrice": 0,
            "tradeCheckedByOwner": false,
            "cpLinkVO": {
                "cpId": "SERVE",
                "mobileArticleUrl": "http://m.serve.co.kr/naver/rd.asp?UID=",
                "mobileArticleLinkTypeCode": "CPNAMEONLY",
                "mobileBmsInspectPassYn": "Y",
                "pcArticleLinkUseAtArticleTitle": false,
                "pcArticleLinkUseAtCpName": false,
                "mobileArticleLinkUseAtArticleTitle": false,
                "mobileArticleLinkUseAtCpName": true,
            },
            "dtlAddrYn": "N",
            "dtlAddr": "",
        },
        {
            "atclNo": "2320212891",
            "cortarNo": "4131010300",
            "atclNm": "빌라",
            "atclStatCd": "R0",
            "rletTpCd": "C02",
            "uprRletTpCd": "C03",
            "rletTpNm": "빌라",
            "tradTpCd": "A1",
            "tradTpNm": "매매",
            "vrfcTpCd": "DOC",
            "flrInfo": "2/4",
            "prc": 25000,
            "rentPrc": 0,
            "hanPrc": "2억 5,000",
            "spc1": "44",
            "spc2": "35.04",
            "direction": "남향",
            "atclCfmYmd": "23.05.12.",
            "lat": 37.604884,
            "lng": 127.13558,
            "atclFetrDesc": "방2.주방.투자추천재개발 동의서 징구중",
            "tagList": ["25년이상", "소형평수", "방두개", "화장실한개"],
            "bildNm": "",
            "minute": 0,
            "sameAddrCnt": 1,
            "sameAddrDirectCnt": 0,
            "cpid": "ten",
            "cpNm": "텐컴즈",
            "cpCnt": 1,
            "rltrNm": "야후공인중개사사무소",
            "directTradYn": "N",
            "minMviFee": 0,
            "maxMviFee": 0,
            "etRoomCnt": 0,
            "tradePriceHan": "",
            "tradeRentPrice": 0,
            "tradeCheckedByOwner": false,
            "cpLinkVO": {
                "cpId": "ten",
                "mobileArticleLinkTypeCode": "NONE",
                "mobileBmsInspectPassYn": "Y",
                "pcArticleLinkUseAtArticleTitle": false,
                "pcArticleLinkUseAtCpName": false,
                "mobileArticleLinkUseAtArticleTitle": false,
                "mobileArticleLinkUseAtCpName": false,
            },
            "dtlAddrYn": "N",
            "dtlAddr": "",
        },
        {
            "atclNo": "2319391356",
            "cortarNo": "4131010300",
            "atclNm": "빌라",
            "atclStatCd": "R0",
            "rletTpCd": "C02",
            "uprRletTpCd": "C03",
            "rletTpNm": "빌라",
            "tradTpCd": "A1",
            "tradTpNm": "매매",
            "vrfcTpCd": "DOC",
            "flrInfo": "2/4",
            "prc": 50000,
            "rentPrc": 0,
            "hanPrc": "5억",
            "spc1": "75",
            "spc2": "65.34",
            "direction": "남동향",
            "atclCfmYmd": "23.05.08.",
            "lat": 37.60319,
            "lng": 127.135733,
            "atclFetrDesc": "투자가치 좋은 빌라,교통편리",
            "tagList": ["25년이내", "방세개", "화장실한개", "중층"],
            "bildNm": "",
            "minute": 0,
            "sameAddrCnt": 1,
            "sameAddrDirectCnt": 0,
            "cpid": "bizmk",
            "cpNm": "매경부동산",
            "cpCnt": 1,
            "rltrNm": "예감좋은부동산공인중개사사무소",
            "directTradYn": "N",
            "minMviFee": 0,
            "maxMviFee": 0,
            "etRoomCnt": 0,
            "tradePriceHan": "",
            "tradeRentPrice": 0,
            "tradeCheckedByOwner": false,
            "cpLinkVO": {
                "cpId": "bizmk",
                "mobileArticleLinkTypeCode": "NONE",
                "mobileBmsInspectPassYn": "Y",
                "pcArticleLinkUseAtArticleTitle": false,
                "pcArticleLinkUseAtCpName": false,
                "mobileArticleLinkUseAtArticleTitle": false,
                "mobileArticleLinkUseAtCpName": false,
            },
            "dtlAddrYn": "N",
            "dtlAddr": "",
        },
        {
            "atclNo": "2318516430",
            "cortarNo": "4131010300",
            "atclNm": "빌라",
            "atclStatCd": "R0",
            "rletTpCd": "C02",
            "uprRletTpCd": "C03",
            "rletTpNm": "빌라",
            "tradTpCd": "A1",
            "tradTpNm": "매매",
            "vrfcTpCd": "DOC",
            "flrInfo": "고/4",
            "prc": 50000,
            "rentPrc": 0,
            "hanPrc": "5억",
            "spc1": "69",
            "spc2": "53.19",
            "direction": "남향",
            "atclCfmYmd": "23.05.02.",
            "lat": 37.602007,
            "lng": 127.139572,
            "atclFetrDesc": "돌다리사거리 인근 빌라 수리비 깎아드려요",
            "tagList": ["25년이상", "방세개", "화장실한개", "고층"],
            "bildNm": "",
            "minute": 0,
            "sameAddrCnt": 1,
            "sameAddrDirectCnt": 0,
            "cpid": "R114",
            "cpNm": "부동산114",
            "cpCnt": 1,
            "rltrNm": "인창어반포레공인중개사사무소",
            "directTradYn": "N",
            "minMviFee": 0,
            "maxMviFee": 0,
            "etRoomCnt": 0,
            "tradePriceHan": "",
            "tradeRentPrice": 0,
            "tradeCheckedByOwner": false,
            "cpLinkVO": {
                "cpId": "R114",
                "mobileArticleUrl": "https://m.r114.com/?_c=redirect&_m=ArticleFromNbp&UID=",
                "mobileArticleLinkTypeCode": "ALL",
                "mobileBmsInspectPassYn": "Y",
                "pcArticleLinkUseAtArticleTitle": false,
                "pcArticleLinkUseAtCpName": false,
                "mobileArticleLinkUseAtArticleTitle": true,
                "mobileArticleLinkUseAtCpName": true,
            },
            "dtlAddrYn": "N",
            "dtlAddr": "",
        },
        {
            "atclNo": "2318581533",
            "cortarNo": "4131010300",
            "atclNm": "빌라",
            "atclStatCd": "R0",
            "rletTpCd": "C02",
            "uprRletTpCd": "C03",
            "rletTpNm": "빌라",
            "tradTpCd": "A1",
            "tradTpNm": "매매",
            "vrfcTpCd": "DOC",
            "flrInfo": "4/4",
            "prc": 30000,
            "rentPrc": 0,
            "hanPrc": "3억",
            "spc1": "55",
            "spc2": "44.19",
            "direction": "서향",
            "atclCfmYmd": "23.05.02.",
            "lat": 37.604917,
            "lng": 127.13897,
            "atclFetrDesc": "급매,올수리 ,구리역 도보이용, 더블역세권.",
            "tagList": ["25년이내", "올수리", "급매", "소형평수"],
            "bildNm": "",
            "minute": 0,
            "sameAddrCnt": 1,
            "sameAddrDirectCnt": 0,
            "cpid": "bizmk",
            "cpNm": "매경부동산",
            "cpCnt": 1,
            "rltrNm": "예감좋은부동산공인중개사사무소",
            "directTradYn": "N",
            "minMviFee": 0,
            "maxMviFee": 0,
            "etRoomCnt": 0,
            "tradePriceHan": "",
            "tradeRentPrice": 0,
            "tradeCheckedByOwner": false,
            "cpLinkVO": {
                "cpId": "bizmk",
                "mobileArticleLinkTypeCode": "NONE",
                "mobileBmsInspectPassYn": "Y",
                "pcArticleLinkUseAtArticleTitle": false,
                "pcArticleLinkUseAtCpName": false,
                "mobileArticleLinkUseAtArticleTitle": false,
                "mobileArticleLinkUseAtCpName": false,
            },
            "dtlAddrYn": "N",
            "dtlAddr": "",
        },
        {
            "atclNo": "2318142917",
            "cortarNo": "4131010300",
            "atclNm": "빌라",
            "atclStatCd": "R0",
            "rletTpCd": "C02",
            "uprRletTpCd": "C03",
            "rletTpNm": "빌라",
            "tradTpCd": "A1",
            "tradTpNm": "매매",
            "vrfcTpCd": "DOC",
            "flrInfo": "1/4",
            "prc": 27000,
            "rentPrc": 0,
            "hanPrc": "2억 7,000",
            "spc1": "50",
            "spc2": "45.81",
            "direction": "동향",
            "atclCfmYmd": "23.04.28.",
            "lat": 37.609333,
            "lng": 127.135068,
            "atclFetrDesc": "전세안고입주매물입니다 24년5월경입주임",
            "tagList": ["25년이내", "1층", "소형평수", "방세개"],
            "bildNm": "",
            "minute": 0,
            "sameAddrCnt": 1,
            "sameAddrDirectCnt": 0,
            "cpid": "bizmk",
            "cpNm": "매경부동산",
            "cpCnt": 1,
            "rltrNm": "뉴미래부동산",
            "directTradYn": "N",
            "minMviFee": 0,
            "maxMviFee": 0,
            "etRoomCnt": 0,
            "tradePriceHan": "",
            "tradeRentPrice": 0,
            "tradeCheckedByOwner": false,
            "cpLinkVO": {
                "cpId": "bizmk",
                "mobileArticleLinkTypeCode": "NONE",
                "mobileBmsInspectPassYn": "Y",
                "pcArticleLinkUseAtArticleTitle": false,
                "pcArticleLinkUseAtCpName": false,
                "mobileArticleLinkUseAtArticleTitle": false,
                "mobileArticleLinkUseAtCpName": false,
            },
            "dtlAddrYn": "N",
            "dtlAddr": "",
        },
        {
            "atclNo": "2318090799",
            "cortarNo": "4131010300",
            "atclNm": "빌라",
            "atclStatCd": "R0",
            "rletTpCd": "C02",
            "uprRletTpCd": "C03",
            "rletTpNm": "빌라",
            "tradTpCd": "A1",
            "tradTpNm": "매매",
            "vrfcTpCd": "DOC",
            "flrInfo": "3/5",
            "prc": 50000,
            "rentPrc": 0,
            "hanPrc": "5억",
            "spc1": "58",
            "spc2": "44.4",
            "direction": "남동향",
            "atclCfmYmd": "23.04.28.",
            "lat": 37.604612,
            "lng": 127.13561,
            "atclFetrDesc": "교통편리,투자가치 높음",
            "tagList": ["25년이상", "소형평수", "방세개", "화장실한개"],
            "bildNm": "",
            "minute": 0,
            "sameAddrCnt": 1,
            "sameAddrDirectCnt": 0,
            "cpid": "bizmk",
            "cpNm": "매경부동산",
            "cpCnt": 1,
            "rltrNm": "예감좋은부동산공인중개사사무소",
            "directTradYn": "N",
            "minMviFee": 0,
            "maxMviFee": 0,
            "etRoomCnt": 0,
            "tradePriceHan": "",
            "tradeRentPrice": 0,
            "tradeCheckedByOwner": false,
            "cpLinkVO": {
                "cpId": "bizmk",
                "mobileArticleLinkTypeCode": "NONE",
                "mobileBmsInspectPassYn": "Y",
                "pcArticleLinkUseAtArticleTitle": false,
                "pcArticleLinkUseAtCpName": false,
                "mobileArticleLinkUseAtArticleTitle": false,
                "mobileArticleLinkUseAtCpName": false,
            },
            "dtlAddrYn": "N",
            "dtlAddr": "",
        },
        {
            "atclNo": "2317779551",
            "cortarNo": "4131010300",
            "atclNm": "빌라",
            "atclStatCd": "R0",
            "rletTpCd": "C02",
            "uprRletTpCd": "C03",
            "rletTpNm": "빌라",
            "tradTpCd": "A1",
            "tradTpNm": "매매",
            "vrfcTpCd": "DOC",
            "flrInfo": "2/4",
            "prc": 29000,
            "rentPrc": 0,
            "hanPrc": "2억 9,000",
            "spc1": "65",
            "spc2": "53.52",
            "direction": "남향",
            "atclCfmYmd": "23.04.26.",
            "repImgUrl": "/20230426_71/land_naver_16824866526340zc4S_JPEG/15178294_202341415413.jpg",
            "repImgTpCd": "10",
            "repImgThumb": "f130_98",
            "lat": 37.606274,
            "lng": 127.138791,
            "atclFetrDesc": "1층 필로티로 주차 가능한 빌라",
            "tagList": ["25년이상", "방세개", "화장실한개"],
            "bildNm": "",
            "minute": 0,
            "sameAddrCnt": 1,
            "sameAddrDirectCnt": 0,
            "cpid": "SERVE",
            "cpNm": "부동산써브",
            "cpCnt": 1,
            "rltrNm": "대박부동산공인중개사사무소",
            "directTradYn": "N",
            "minMviFee": 0,
            "maxMviFee": 0,
            "etRoomCnt": 0,
            "tradePriceHan": "",
            "tradeRentPrice": 0,
            "tradeCheckedByOwner": false,
            "cpLinkVO": {
                "cpId": "SERVE",
                "mobileArticleUrl": "http://m.serve.co.kr/naver/rd.asp?UID=",
                "mobileArticleLinkTypeCode": "CPNAMEONLY",
                "mobileBmsInspectPassYn": "Y",
                "pcArticleLinkUseAtArticleTitle": false,
                "pcArticleLinkUseAtCpName": false,
                "mobileArticleLinkUseAtArticleTitle": false,
                "mobileArticleLinkUseAtCpName": true,
            },
            "dtlAddrYn": "N",
            "dtlAddr": "",
        },
        {
            "atclNo": "2317842902",
            "cortarNo": "4131010300",
            "atclNm": "빌라",
            "atclStatCd": "R0",
            "rletTpCd": "C02",
            "uprRletTpCd": "C03",
            "rletTpNm": "빌라",
            "tradTpCd": "A1",
            "tradTpNm": "매매",
            "vrfcTpCd": "DOC",
            "flrInfo": "2/4",
            "prc": 29000,
            "rentPrc": 0,
            "hanPrc": "2억 9,000",
            "spc1": "65",
            "spc2": "53.52",
            "direction": "남향",
            "atclCfmYmd": "23.04.26.",
            "repImgUrl": "/20230512_283/land_naver_1683861488879mAuv7_JPEG/15168680_202351212112610.jpg",
            "repImgTpCd": "10",
            "repImgThumb": "f130_98",
            "lat": 37.606274,
            "lng": 127.138791,
            "atclFetrDesc": "공실 즉시입주 주차가능 초역세권 도보 5분 실거주겸 투자",
            "tagList": ["25년이상", "방세개", "화장실한개"],
            "bildNm": "",
            "minute": 0,
            "sameAddrCnt": 1,
            "sameAddrDirectCnt": 0,
            "cpid": "SERVE",
            "cpNm": "부동산써브",
            "cpCnt": 1,
            "rltrNm": "구리역수자인홈런공인중개사",
            "directTradYn": "N",
            "minMviFee": 0,
            "maxMviFee": 0,
            "etRoomCnt": 0,
            "tradePriceHan": "",
            "tradeRentPrice": 0,
            "tradeCheckedByOwner": false,
            "cpLinkVO": {
                "cpId": "SERVE",
                "mobileArticleUrl": "http://m.serve.co.kr/naver/rd.asp?UID=",
                "mobileArticleLinkTypeCode": "CPNAMEONLY",
                "mobileBmsInspectPassYn": "Y",
                "pcArticleLinkUseAtArticleTitle": false,
                "pcArticleLinkUseAtCpName": false,
                "mobileArticleLinkUseAtArticleTitle": false,
                "mobileArticleLinkUseAtCpName": true,
            },
            "dtlAddrYn": "N",
            "dtlAddr": "",
        },
        {
            "atclNo": "2317352876",
            "cortarNo": "4131010300",
            "atclNm": "빌라",
            "atclStatCd": "R0",
            "rletTpCd": "C02",
            "uprRletTpCd": "C03",
            "rletTpNm": "빌라",
            "tradTpCd": "A1",
            "tradTpNm": "매매",
            "vrfcTpCd": "DOC",
            "flrInfo": "2/3",
            "prc": 25000,
            "rentPrc": 0,
            "hanPrc": "2억 5,000",
            "spc1": "44",
            "spc2": "35.04",
            "direction": "서향",
            "atclCfmYmd": "23.04.24.",
            "lat": 37.604884,
            "lng": 127.13558,
            "atclFetrDesc": "투자가치 좋은 다세대주택",
            "tagList": ["25년이상", "소형평수", "방두개", "화장실한개"],
            "bildNm": "",
            "minute": 0,
            "sameAddrCnt": 1,
            "sameAddrDirectCnt": 0,
            "cpid": "SERVE",
            "cpNm": "부동산써브",
            "cpCnt": 1,
            "rltrNm": "대림e부동산공인중개사사무소",
            "directTradYn": "N",
            "minMviFee": 0,
            "maxMviFee": 0,
            "etRoomCnt": 0,
            "tradePriceHan": "",
            "tradeRentPrice": 0,
            "tradeCheckedByOwner": false,
            "cpLinkVO": {
                "cpId": "SERVE",
                "mobileArticleUrl": "http://m.serve.co.kr/naver/rd.asp?UID=",
                "mobileArticleLinkTypeCode": "CPNAMEONLY",
                "mobileBmsInspectPassYn": "Y",
                "pcArticleLinkUseAtArticleTitle": false,
                "pcArticleLinkUseAtCpName": false,
                "mobileArticleLinkUseAtArticleTitle": false,
                "mobileArticleLinkUseAtCpName": true,
            },
            "dtlAddrYn": "N",
            "dtlAddr": "",
        },
    ],
}
