{
    "code": "success",
    "hasPaidPreSale": false,
    "more": false,
    "TIME": false,
    "z": 14,
    "page": 2,
    "body": [
        {
            "atclNo": "2317274365",
            "cortarNo": "4136011200",
            "atclNm": "빌라",
            "atclStatCd": "R0",
            "rletTpCd": "C02",
            "uprRletTpCd": "C03",
            "rletTpNm": "빌라",
            "tradTpCd": "A1",
            "tradTpNm": "매매",
            "vrfcTpCd": "OWNER",
            "flrInfo": "3/3",
            "prc": 50000,
            "rentPrc": 0,
            "hanPrc": "5억",
            "spc1": "69",
            "spc2": "69.57",
            "direction": "서향",
            "atclCfmYmd": "23.04.22.",
            "lat": 37.606802,
            "lng": 127.161476,
            "atclFetrDesc": "다산동 재개발 원일빌라 현 월세",
            "tagList": ["25년이상", "역세권", "탑층", "방세개"],
            "bildNm": "",
            "minute": 0,
            "sameAddrCnt": 1,
            "sameAddrDirectCnt": 0,
            "cpid": "SERVE",
            "cpNm": "부동산써브",
            "cpCnt": 1,
            "rltrNm": "미스터홈즈부동산중개다산센터",
            "directTradYn": "N",
            "minMviFee": 0,
            "maxMviFee": 0,
            "etRoomCnt": 0,
            "tradePriceHan": "",
            "tradeRentPrice": 0,
            "tradeCheckedByOwner": false,
            "cpLinkVO": {
                "cpId": "SERVE",
                "mobileArticleUrl": "http://m.serve.co.kr/naver/rd.asp?UID=",
                "mobileArticleLinkTypeCode": "CPNAMEONLY",
                "mobileBmsInspectPassYn": "Y",
                "pcArticleLinkUseAtArticleTitle": false,
                "pcArticleLinkUseAtCpName": false,
                "mobileArticleLinkUseAtArticleTitle": false,
                "mobileArticleLinkUseAtCpName": true,
            },
            "dtlAddrYn": "N",
            "dtlAddr": "",
            "point": 440,
        },
        {
            "atclNo": "2317829719",
            "cortarNo": "4136011200",
            "atclNm": "연립",
            "atclStatCd": "R0",
            "rletTpCd": "C02",
            "uprRletTpCd": "C03",
            "rletTpNm": "빌라",
            "tradTpCd": "A1",
            "tradTpNm": "매매",
            "vrfcTpCd": "DOC",
            "flrInfo": "2/3",
            "prc": 60000,
            "rentPrc": 0,
            "hanPrc": "6억",
            "spc1": "85",
            "spc2": "69.57",
            "direction": "남서향",
            "atclCfmYmd": "23.04.26.",
            "lat": 37.606802,
            "lng": 127.161476,
            "atclFetrDesc": "재개발 관리처분임박",
            "tagList": ["25년이상", "역세권", "방두개", "화장실한개"],
            "bildNm": "",
            "minute": 0,
            "sameAddrCnt": 1,
            "sameAddrDirectCnt": 0,
            "cpid": "ten",
            "cpNm": "텐컴즈",
            "cpCnt": 1,
            "rltrNm": "다산나눔공인중개사사무소",
            "directTradYn": "N",
            "minMviFee": 0,
            "maxMviFee": 0,
            "etRoomCnt": 0,
            "tradePriceHan": "",
            "tradeRentPrice": 0,
            "tradeCheckedByOwner": false,
            "cpLinkVO": {
                "cpId": "ten",
                "mobileArticleLinkTypeCode": "NONE",
                "mobileBmsInspectPassYn": "Y",
                "pcArticleLinkUseAtArticleTitle": false,
                "pcArticleLinkUseAtCpName": false,
                "mobileArticleLinkUseAtArticleTitle": false,
                "mobileArticleLinkUseAtCpName": false,
            },
            "dtlAddrYn": "N",
            "dtlAddr": "",
            "point": 310,
        },
        {
            "atclNo": "2317484917",
            "cortarNo": "4136011200",
            "atclNm": "연립",
            "atclStatCd": "R0",
            "rletTpCd": "C02",
            "uprRletTpCd": "C03",
            "rletTpNm": "빌라",
            "tradTpCd": "A1",
            "tradTpNm": "매매",
            "vrfcTpCd": "NONE",
            "flrInfo": "1/3",
            "prc": 60000,
            "rentPrc": 0,
            "hanPrc": "6억",
            "spc1": "63",
            "spc2": "55.5",
            "direction": "남동향",
            "atclCfmYmd": "23.04.24.",
            "lat": 37.606541,
            "lng": 127.160784,
            "atclFetrDesc": "역세권  재개발구역",
            "tagList": ["25년이상", "역세권", "1층", "방세개"],
            "bildNm": "",
            "minute": 0,
            "sameAddrCnt": 1,
            "sameAddrDirectCnt": 0,
            "cpid": "KAR",
            "cpNm": "한국공인중개사협회",
            "cpCnt": 1,
            "rltrNm": "탑스공인중개사사무소",
            "directTradYn": "N",
            "minMviFee": 0,
            "maxMviFee": 0,
            "etRoomCnt": 0,
            "tradePriceHan": "",
            "tradeRentPrice": 0,
            "tradeCheckedByOwner": false,
            "cpLinkVO": {
                "cpId": "KAR",
                "mobileArticleLinkTypeCode": "NONE",
                "mobileBmsInspectPassYn": "Y",
                "pcArticleLinkUseAtArticleTitle": false,
                "pcArticleLinkUseAtCpName": false,
                "mobileArticleLinkUseAtArticleTitle": false,
                "mobileArticleLinkUseAtCpName": false,
            },
            "dtlAddrYn": "N",
            "dtlAddr": "",
            "point": -560,
        },
        {
            "atclNo": "2317538099",
            "cortarNo": "4136011200",
            "atclNm": "빌라",
            "atclStatCd": "R0",
            "rletTpCd": "C02",
            "uprRletTpCd": "C03",
            "rletTpNm": "빌라",
            "tradTpCd": "A1",
            "tradTpNm": "매매",
            "vrfcTpCd": "DOC",
            "flrInfo": "고/4",
            "prc": 65000,
            "rentPrc": 0,
            "hanPrc": "6억 5,000",
            "spc1": "80",
            "spc2": "75",
            "direction": "남향",
            "atclCfmYmd": "23.04.25.",
            "lat": 37.605402,
            "lng": 127.159034,
            "tagList": ["25년이상", "방세개", "화장실두개", "고층"],
            "bildNm": "",
            "minute": 0,
            "sameAddrCnt": 1,
            "sameAddrDirectCnt": 0,
            "cpid": "SERVE",
            "cpNm": "부동산써브",
            "cpCnt": 1,
            "rltrNm": "도시인의꿈공인중개사사무소",
            "directTradYn": "N",
            "minMviFee": 0,
            "maxMviFee": 0,
            "etRoomCnt": 0,
            "tradePriceHan": "",
            "tradeRentPrice": 0,
            "tradeCheckedByOwner": false,
            "cpLinkVO": {
                "cpId": "SERVE",
                "mobileArticleUrl": "http://m.serve.co.kr/naver/rd.asp?UID=",
                "mobileArticleLinkTypeCode": "CPNAMEONLY",
                "mobileBmsInspectPassYn": "Y",
                "pcArticleLinkUseAtArticleTitle": false,
                "pcArticleLinkUseAtCpName": false,
                "mobileArticleLinkUseAtArticleTitle": false,
                "mobileArticleLinkUseAtCpName": true,
            },
            "dtlAddrYn": "N",
            "dtlAddr": "",
            "point": 290,
        },
        {
            "atclNo": "2317538155",
            "cortarNo": "4136011200",
            "atclNm": "연립",
            "atclStatCd": "R0",
            "rletTpCd": "C02",
            "uprRletTpCd": "C03",
            "rletTpNm": "빌라",
            "tradTpCd": "A1",
            "tradTpNm": "매매",
            "vrfcTpCd": "DOC",
            "flrInfo": "고/3",
            "prc": 70000,
            "rentPrc": 0,
            "hanPrc": "7억",
            "spc1": "90",
            "spc2": "69.36",
            "direction": "남동향",
            "atclCfmYmd": "23.04.25.",
            "lat": 37.605127,
            "lng": 127.159232,
            "atclFetrDesc": "지금도농6의2구역 매매 정보자료 보유 제공",
            "tagList": ["25년이상", "방세개", "화장실한개", "고층"],
            "bildNm": "",
            "minute": 0,
            "sameAddrCnt": 1,
            "sameAddrDirectCnt": 0,
            "cpid": "SERVE",
            "cpNm": "부동산써브",
            "cpCnt": 1,
            "rltrNm": "도시인의꿈공인중개사사무소",
            "directTradYn": "N",
            "minMviFee": 0,
            "maxMviFee": 0,
            "etRoomCnt": 0,
            "tradePriceHan": "",
            "tradeRentPrice": 0,
            "tradeCheckedByOwner": false,
            "cpLinkVO": {
                "cpId": "SERVE",
                "mobileArticleUrl": "http://m.serve.co.kr/naver/rd.asp?UID=",
                "mobileArticleLinkTypeCode": "CPNAMEONLY",
                "mobileBmsInspectPassYn": "Y",
                "pcArticleLinkUseAtArticleTitle": false,
                "pcArticleLinkUseAtCpName": false,
                "mobileArticleLinkUseAtArticleTitle": false,
                "mobileArticleLinkUseAtCpName": true,
            },
            "dtlAddrYn": "N",
            "dtlAddr": "",
            "point": 290,
        },
    ],
}
