{
    "articleNo": "2322021832",
    "articleName": "빌라",
    "articleStatus": "R0",
    "realEstateTypeCode": "VL",
    "realEstateTypeName": "빌라",
    "articleRealEstateTypeCode": "C03",
    "articleRealEstateTypeName": "빌라/연립",
    "tradeTypeCode": "A1",
    "tradeTypeName": "매매",
    "verificationTypeCode": "MOBL",
    "floorInfo": "5/5",
    "priceChangeState": "SAME",
    "isPriceModification": False,
    "dealOrWarrantPrc": "2억",
    "area1": 72,
    "area2": 72,
    "direction": "남향",
    "articleConfirmYmd": "20230525",
    "siteImageCount": 0,
    "articleFeatureDesc": "엘리베이터 있음 집깨끗 입주협의",
    "tagList": ["10년이내", "탑층", "방세개", "화장실두개"],
    "sameAddrCnt": 1,
    "sameAddrDirectCnt": 0,
    "sameAddrMaxPrc": "2억",
    "sameAddrMinPrc": "2억",
    "cpid": "bizmk",
    "cpName": "매경부동산",
    "cpPcArticleLinkUseAtArticleTitleYn": False,
    "cpPcArticleLinkUseAtCpNameYn": False,
    "cpMobileArticleLinkUseAtArticleTitleYn": False,
    "cpMobileArticleLinkUseAtCpNameYn": False,
    "latitude": "37.665291",
    "longitude": "127.300421",
    "isLocationShow": False,
    "realtorName": "한샘공인중개사사무소",
    "realtorId": "yja8303",
    "tradeCheckedByOwner": False,
    "isDirectTrade": False,
    "isInterest": False,
    "isComplex": False,
}
