{
    "articleNo": "2322021832",
    "articleName": "빌라",
    "articleSubName": "A동",
    "cpId": "bizmk",
    "cortarNo": "4136025600",
    "tradeBuildingTypeCode": "ROOM",
    "exposeStartYMD": "20230525",
    "exposeEndYMD": "20230624",
    "articleConfirmYMD": "20230525",
    "tradeCompleteYN": "N",
    "totalDongCount": 0,
    "buildingTypeName": "빌라",
    "articleStatusCode": "R0",
    "articleTypeCode": "C02",
    "realestateTypeCode": "VL",
    "realestateTypeName": "빌라",
    "tradeTypeCode": "A1",
    "tradeTypeName": "매매",
    "verificationTypeCode": "MOBL",
    "verificationTypeName": "집주인",
    "applyYN": "N",
    "directTradeYN": "N",
    "mapLocationIndicationYn": "Y",
    "latitude": "37.6652911",
    "longitude": "127.3004209",
    "pnu": "4136025622101400021",
    "cityNo": "4100000000",
    "cityName": "경기도",
    "divisionName": "남양주시",
    "sectionName": "화도읍",
    "realtorId": "yja8303",
    "walkingTimeToNearSubway": 0,
    "grandPlanList": [],
    "detailAddress": "",
    "liAddress": "묵현리",
    "jibunAddress": "140-21",
    "jibunAddressExposureYn": "N",
    "etcAddress": "A동  502호",
    "exposureAddress": "경기도 남양주시 화도읍 묵현리 140-21",
    "virtualAddressYn": "N",
    "roomCount": "3",
    "bathroomCount": "2",
    "householdCount": "8",
    "moveInTypeCode": "MV001",
    "moveInTypeName": "즉시입주",
    "moveInDiscussionPossibleYN": "협의가능",
    "moveInPossibleYmd": "20230705",
    "monthlyManagementCost": 0,
    "buildingSubName": "A동",
    "buildingTypeCode": "C0203",
    "articleFeatureDescription": "엘리베이터 있음 집깨끗 입주협의",
    "parkingCount": 8,
    "parkingPossibleYN": "Y",
    "duplexYN": "N",
    "floorLayerName": "단층",
    "hasBuildingUnitInfo": False,
    "lawUsage": "공동주택",
    "tagList": ["10년이내", "탑층", "방세개", "화장실두개"],
    "isInterest": False,
    "isFalseHoodDeclared": False,
    "kisoConnectionYN": "Y",
    "detailAddressYn": "N",
    "isComplex": False,
    "isOwnerTradeCompleted": False,
}
