VL = {
    "atclNo": "2317652285",
    "cortarNo": "4182032500",
    "atclNm": "빌라",
    "atclStatCd": "R0",
    "rletTpCd": "C02",
    "uprRletTpCd": "C03",
    "rletTpNm": "빌라",
    "tradTpCd": "A1",
    "tradTpNm": "매매",
    "vrfcTpCd": "DOC",
    "flrInfo": "중/5",
    "prc": 21500,
    "rentPrc": 0,
    "hanPrc": "2억 1,500",
    "spc1": "55",
    "spc2": "47.59",
    "direction": "남동향",
    "atclCfmYmd": "23.04.25.",
    "lat": 37.737545,
    "lng": 127.420906,
    "atclFetrDesc": "언제든연락주세요",
    "tagList": ["2년이내", "소형평수", "방세개", "화장실두개"],
    "bildNm": "",
    "minute": 0,
    "sameAddrCnt": 1,
    "sameAddrDirectCnt": 0,
    "cpid": "bizmk",
    "cpNm": "매경부동산",
    "cpCnt": 1,
    "rltrNm": "행운공인중개사",
    "directTradYn": "N",
    "minMviFee": 0,
    "maxMviFee": 0,
    "etRoomCnt": 0,
    "tradePriceHan": "",
    "tradeRentPrice": 0,
    "tradeCheckedByOwner": false,
    "cpLinkVO": {
        "cpId": "bizmk",
        "mobileArticleLinkTypeCode": "NONE",
        "mobileBmsInspectPassYn": "Y",
        "pcArticleLinkUseAtArticleTitle": false,
        "pcArticleLinkUseAtCpName": false,
        "mobileArticleLinkUseAtArticleTitle": false,
        "mobileArticleLinkUseAtCpName": false,
    },
    "dtlAddrYn": "N",
    "dtlAddr": "",
}
