APT = {
    "atclNo": "2318891720",
    "cortarNo": "4182025000",
    "atclNm": "준수",
    "atclStatCd": "R0",
    "rletTpCd": "A01",
    "uprRletTpCd": "A01",
    "rletTpNm": "아파트",
    "tradTpCd": "A1",
    "tradTpNm": "매매",
    "vrfcTpCd": "NONE",
    "flrInfo": "중/6",
    "prc": 10500,
    "rentPrc": 0,
    "hanPrc": "1억 500",
    "spc1": "84",
    "spc2": "60",
    "direction": "북향",
    "atclCfmYmd": "23.05.03.",
    "lat": 37.834058,
    "lng": 127.508908,
    "tagList": ["25년이상", "방세개", "화장실두개", "중층"],
    "bildNm": "A동",
    "minute": 0,
    "sameAddrCnt": 1,
    "sameAddrDirectCnt": 0,
    "cpid": "KAR",
    "cpNm": "한국공인중개사협회",
    "cpCnt": 1,
    "rltrNm": "가평부동산공인중개사사무소",
    "directTradYn": "N",
    "minMviFee": 0,
    "maxMviFee": 0,
    "etRoomCnt": 0,
    "tradePriceHan": "",
    "tradeRentPrice": 0,
    "tradeCheckedByOwner": false,
    "cpLinkVO": {
        "cpId": "KAR",
        "mobileArticleLinkTypeCode": "NONE",
        "mobileBmsInspectPassYn": "Y",
        "pcArticleLinkUseAtArticleTitle": false,
        "pcArticleLinkUseAtCpName": false,
        "mobileArticleLinkUseAtArticleTitle": false,
        "mobileArticleLinkUseAtCpName": false,
    },
    "dtlAddrYn": "N",
    "dtlAddr": "",
}
